### ISSUE TITLE
Output order on the filtered ls challenge

### ISSUE THREAD

**Issue by wilsonsilva** [workshopper/learnyounode#107]
The following code does what is asked, but does not solve the challenge. The problem is that learnyounode tests expect an ordered output, and by popping the filenames the output order is reversed.

``` javascript
var fs = require('fs'),
    path = require ('path'),
    directory = process.argv[2],
    extension = process.argv[3];

fs.readdir(directory, function (err, filenames) {
  while(filenames.length) {
    var filename = filenames.pop(); // replace pop() with shift() to make it pass
    if (path.extname(filename) == '.' + extension) {
      console.log(filename);
    }
  }
});
```

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
