### ISSUE TITLE
Won't run on Linux (Debian based)

### ISSUE THREAD

**Issue by EwanValentine** [workshopper/learnyounode#11]
running learnyounode doesn't return anything in terminal in Linux Mint 15 (fresh install of node.js)

**Comment by RahulSDeshpande** [comment]
Hi all..

Seems like I solved this issue..

Thanks to @sidorares..

The solution for @EwanValentine's issue is:

**You need to remove '_node_' application from your Linux [may be Debian]**..
```
sudo apt-get remove node
```

As I think, terminal may be getting confused between _node_ & _nodejs_..

Command ```vim learnyounode``` will work perfectly as it worked for me :P

Please do comment if any further issues.. :)

Cheers..
Happy Coding..

**Comment by Sal56** [comment]
when you install learnyounode with 
`npm -g install learnyounode` 
it will list the installation directory as a path from your home directory just copy and paste the full install path into the command line and you should get learnyounode to run. 
for example;
`/home/yourusername/.node_modules_global/learnyounode`
You can also add this to your $PATH environment variable then all you have to type is learnyounode at the command line
