### ISSUE TITLE
suggest a learnyounode book

### ISSUE THREAD

**Issue by L2L2L** [workshopper/learnyounode#114]
I suggest a learn you node book. This tutorial is great, but there should be a book before it. A book for new comers. I'm not saying write a book, I'm saying take this tutorial and compose it into a book, change the example to not give away the answer, but smiler similar to where one can compare. Give it a strength "here what this do, and you write it like this" feel. Then you can publish another book that goes into dept. Let the first book be around 200 pages, mostly feel with code example, and follow along. Than after the person finish the around 200 pages book, direct them to the learnyounode module. With this, you will have given them an over view of each lesson indirectly, allow them to feel more comfortable. Than just having lesson after lesson of "figure it out yourself", and going to the discussion forums to asks question after question after question.... BOOK!

title: Learn You Node
subtitle: For much win!
page count: 200 - 250

**Comment by AnshulMalik** [comment]
I think there are plenty of good resources available now, so it won't be much difficult for people to figure out.

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
