### ISSUE TITLE
Used fs method other than fs.createReadStream(): fs.createReadStream()

### ISSUE THREAD

**Issue by CraigBryan** [workshopper/learnyounode#122]
The following code: 

``` javascript
var http = require('http');
var fs = require('fs');
var src = fs.createReadStream(process.argv[3]);
var server = http.createServer(function (request, response)
  {
    src.pipe(response);
  });
server.listen(process.argv[2]);
```

passes exercise 11, HTTP File Server, but also gives the error:
`Used fs method other than fs.createReadStream(): fs.createReadStream()`.

![false_fs_error](https://cloud.githubusercontent.com/assets/3247893/4325906/06d5c7e0-3f6a-11e4-9603-e350315f9dc4.jpg)

**Comment by rusikf** [comment]
@rvagg , why we must call ```fs.createReadStream()``` in callback? Yes it is the official solution, but task started with:

> Write an HTTP server that serves the **same text file** for each request it receives.

So, why we must create ReadStream again on each request if file is the same on each request ?

> you need to make a new one each time it's used

Why? I think it is true, if stream is changing depending on request , no ?

**Comment by ralphtheninja** [comment]
@rusikf If you try it you'll find out that you really do need to `fs.createReadStream()` for _each_ request. It works on the first request, but not on consecutive requests.

**Comment by rusikf** [comment]
@ralphtheninja , thanks for response !

**Comment by ralphtheninja** [comment]
@rvagg what is the correct with dealing with problems like this? run the test twice? :)

**Comment by CodeMan99** [comment]
Could someone please explain this more clearly? I thought streams were intended to be reusable. Consider the following.

```javascript
var fs = require('fs');
var src = fs.createReadStream('./program01.js');

console.log('1'); src.on('end', () => console.log('end 1')).pipe(process.stdout);
console.log('2'); src.on('end', () => console.log('end 2')).pipe(process.stdout);
console.log('3'); src.on('end', () => console.log('end 3')).pipe(process.stdout);
console.log('4'); src.on('end', () => console.log('end 4')).pipe(process.stdout);
```

Will print

```
1
2
3
4
console.log('HELLO WORLD');
console.log('HELLO WORLD');
console.log('HELLO WORLD');
console.log('HELLO WORLD');
end 1
end 2
end 3
end 4
```

This seems correct to me. Am I missing something?

**Comment by martinheidegger** [comment]
@CodeMan99 Your example works because all piping is done at the same time, consider this:

```javascript
var fs = require('fs');
var src = fs.createReadStream('./program01.js');

console.log('1'); src.on('end', () => console.log('end 1')).pipe(process.stdout);
setTimeout(() => { console.log('2'); src.on('end', () => console.log('end 2')).pipe(process.stdout) }, 20);
setTimeout(() => { console.log('3'); src.on('end', () => console.log('end 3')).pipe(process.stdout) }, 200);
setTimeout(() => { console.log('4'); src.on('end', () => console.log('end 4')).pipe(process.stdout) }, 2000);
```

**Comment by CodeMan99** [comment]
@martinheidegger Ah. Do you happen to know how to use [`cloneable-readable`](https://github.com/mcollina/cloneable-readable) to get around that issue? In my attempts to use `cloneable-readable` I cannot seem to get data to flow.

**Comment by martinheidegger** [comment]
I wouldn't call it an issue, its how streams are working. They do not load the whole file but rather parts of it at a time to make it possible to work with data that is bigger than your available system memory. The easiest solution in some cases might be just a fat arrow function: `src = () => fs.createReadStream('./program01.js')` then you can create a new source-stream everytime you need it.

**Comment by CodeMan99** [comment]
Ok, well the use case I'm thinking of is a pretty IO intensive pipeline. Cloning seems like the right tool for that job. Issue or not, it is something I'd like to know how to work around in multiple ways.

**Comment by martinheidegger** [comment]
Creating a new stream and cloning is about same, performance wise.

**Comment by CodeMan99** [comment]
Not if your pipeline includes network IO.

**Comment by martinheidegger** [comment]
When you stream data to the client, you need to make sure that the right bits and pieces arrive at the right time, a stream (as used in node) keeps track of the position of the reader as well. In order to allow unlimited sizes of data to be streamed. You can improve the performance of often accessed streams by caching parts of them (in memory of on disk) but when reading the data you still need to provide a coherent stream. There are more complex implementations of stream available for node is that might suite your use case but they all focus on the same underlying principle thaught in learnyounode which is that there is this stream API which expects one fresh stream per request.

**Comment by CodeMan99** [comment]
Ok martin. Thanks for not answering my question again.

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
