### ISSUE TITLE
Failed to load the learnyounode module in Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by minmon** [workshopper/learnyounode#134]
This module had been installed on Ubuntu 14.04 LTS by global.
I tried to load this module from terminal but I seen anyting
instanceof the learnyounode's screen. Why ?

**Comment by oscarbatlle** [comment]
This is how you do it : 

- Use npm in order to upgrade node.

sudo npm cache clean -f
sudo npm install -g n
sudo n stable
