### ISSUE TITLE
Make it modular: "Your additional module file returned an error on its callback:"

### ISSUE THREAD

**Issue by vampsama** [workshopper/learnyounode#136]
I bet there is some basic node/javascript Im missing that is causing this...

verify result:

``` javascript
                 ACTUAL                                  EXPECTED                 
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

✓ Submission results match expected
✓ Additional module file exports a single function
✓ Additional module file exports a function that takes 3 arguments
✓ Additional module file handles errors properly
✓ Additional module file handles callback argument
✗ Your additional module file [filteredls.js] returned an error on its callback:
    'CHANGELOG.md'
✗ Your additional module file [filteredls.js] returned an error on its callback:
    'LICENCE.md'

/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:152
    processors[i].call(self, mode, function (err, pass) {
                  ^
TypeError: Cannot call method 'call' of undefined
    at next (/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:152:19)
    at /usr/local/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:159:7
    at callback (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:25:15)
    at modFileError (/usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:30:5)
    at /usr/local/lib/node_modules/learnyounode/exercises/make_it_modular/verify.js:103:18
    at /Users/john/learnyounode/filteredls.js:9:9
    at Object.oncomplete (fs.js:107:15)
```

makeitmodular.js:

``` javascript
var mymodule = require('./filteredls.js');
mymodule(process.argv[2], process.argv[3], function(err, data){ 
  if(err){
    console.log(err);
  } else {
    console.log(data);
}
});
```

filteredls.js:

``` javascript
module.exports = function (dirPath, filterString, callback){
  var fs = require('fs');
  fs.readdir(dirPath, function (err ,data){
    if(err) {
      return callback(err);
    }
    for(i = 0; i < data.length; i++){
       if(data[i].split('.')[1] === filterString){
        callback(data[i]);
      }
    }
  });
}
```

**Comment by phi1ipp** [comment]
Using `data[i].split('.')[1] === filterString` is not a proper solution to filter by extension in case you have a file like name.subname.ext 

`path.extName(file) === '.' + filterExt` is better

**Comment by NeXTs** [comment]
same issue here, what may be wrong?

```
var getFolder = require('./getFolder');

getFolder(process.argv[2], process.argv[3], function(err, result) {
  if( ! err) console.log(result)
})
```

```
var fs = require('fs');
var path = require('path');

module.exports = function(dirname, extname, cb) {
  if(extname[0] != '.') extname = '.' + extname;
  fs.readdir(dirname, function(err, list) {
    if(err) return cb(err);

    list.forEach(function(item) {
      if(path.extname(item) == extname) cb(null, item)
    })
  })  
}
```


> C:\Users\me\AppData\Roaming\npm\node_modules\learnyounode\node_modules\workshopper-exercise\exercise.js:188
    processors[i].call(self, mode, function (err, pass) {
                 ^
TypeError: Cannot read property 'call' of undefined

**Comment by fkorssjoen** [comment]
Hi @NeXTs , I'm having the same issue here, but when I run the js as a standalone it works fine, and the code is very similar as yours. Did you realize there was a bug in your code, or the problem was with learnyounode? 

I don't wanna write the code "literally" as learn you node wants.

**Comment by NeXTs** [comment]
@fkorssjoen Seems to be it was some learnynode's bug. I just skipped those 'broken' tasks.

**Comment by nbappi** [comment]
output file : output.js
--------------------------------------------------------------------------------------
var modules = require("./files");
var dirname = process.argv[2] ;
var extname = process.argv[3] ;

modules( dirname ,extname , function (err , datas)
{
     datas.forEach(function(data){
           console.log(data);
      });
});

module file : files.js
----------------------------------------------------------------------------------
var fs = require("fs"), path = require("path");
module.exports = function(dirname, extname, callback)
{
fs.readdir(dirname , function( err , files)
{
    if(err) return callback(err);

    files = files.filter(function (file){
          return path.extname(file) == '.'+extname;
    });
     callback(null, files);
 });    
}

**Comment by Hyllesen** [comment]
Still having this bug with my code. Seems like a learnyounodejs problem. Perhaps the binding is not correct.
