### ISSUE TITLE
Question about the official solution in exercise 9

### ISSUE THREAD

**Issue by rcanepa** [workshopper/learnyounode#140]
The problem is:

"This problem is the same as the previous problem (HTTP COLLECT) in that you need to use http.get(). However, this time you will be provided with three URLs as the first three command-line arguments.

You must collect the complete content provided to you by each of the URLs and print it to the console (stdout). You don't need to print out the length, just the data as a String; one line per URL. The catch is that you must print them out in the same order as the URLs are provided to you as command-line arguments."

And the official solution is:

``` javascript
var http = require('http')
    var bl = require('bl')
    var results = []
    var count = 0

    function printResults () {
      for (var i = 0; i < 3; i++)
        console.log(results[i])
    }

    function httpGet (index) {
      http.get(process.argv[2 + index], function (response) {
        response.pipe(bl(function (err, data) {
          if (err)
            return console.error(err)

          results[index] = data.toString()
          count++

          if (count == 3) // yay! we are the last one!
            printResults()
        }))
      })
    }

    for (var i = 0; i < 3; i++)
      httpGet(i)
```

How is this solution always printing the results in the correct order if is using a for loop approach?. Clearly I am not seeing how the request chain is working in the example, is it working because of the bl module?

Thanks in advance.

Renzo

**Comment by omundy** [comment]
```"you must print [the data from the urls] out in the same order as the URLs are provided to you as command-line arguments."```

The OP perhaps made the same mistake I did, which was to assume that the data from the get method needed to be printed in the order *returned from the servers* (thus providing a real-world example of why async is important). But I see now after scrutinizing the instructions that it wants data *in the order the args were provided.* Seems like it would be the other way around given the title of the lesson, no?

**Comment by Young1906** [comment]
Is this a good way to write it? 
```javascript 
  1 var http = require('http');
  2 var bl = require('bl');
  3 var urls = process.argv.slice(2);
  4 var rs = [];
  5 var i = 0;
  6 
  7 function get(urls){
  8     http.get(urls[i],function(res){
  9         res.pipe(bl(function(err,data){
 10             if (err) throw err;
 11             console.log(data.toString());
 12             i++;
 13             if(i < 3) get(urls);
 14         }))
 15     })
 16 }
 17 
 18 get(urls);                                      
```

**Comment by suhailbinabdullah** [comment]
**_**_I am getting this error.... please help_**_**

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 127.0.0.1:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
