### ISSUE TITLE
HTTP JSON API SERVER - Final solution is inconsistent with earlier exercise handling date/time padding

### ISSUE THREAD

**Issue by Varedis** [workshopper/learnyounode#142]
The solution for Exercise 10 tells us that the dates and times need to be padded and implements a function for prefixing any time or date less than 10 with a leading 0.

This formula isn't adhered to in Exercise 13 however and causes my final build to fail even though it is a correct (hh:mm:ss) time.

Luckily for me this was just seconds causing the issue so I could wait a few seconds and rerun and it would pass.

The final solution should implement the zeroFill function and it should be made more clear in the description the formatting expected from the values.

**Comment by RichardBansal** [comment]
I am not totally clear on the date portion of the problem. My response is as follows:

1.  ACTUAL:    "{\"hour\":17,\"minute\":7,\"second\":8}"
1.  EXPECTED:  "{\"hour\":17,\"minute\":5,\"second\":28}"

I must be missing something fundamental here, I am checking for the GET request and responding with a JSON data, however it is slightly off.

**Comment by rvagg** [comment]
@RichardBansal are you responding with the time contained in the `ido` query string value? A mistake that a lot of people make here is to respond with the _current_ time and not the time fed in, they will be different in order to check that you're doing what's been asked.

**Comment by RichardBansal** [comment]
@rvagg That maybe the mistake, let me see if I can grab the time fed in, will keep you posted, perhaps share my code.

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
