### ISSUE TITLE
make it modular bug?

### ISSUE THREAD

**Issue by jasand** [workshopper/learnyounode#143]
Your additional module file [mymodule.js] did not return an Array with the correct number of elements as the second argument of the callback
# FAIL

The module:

``` javascript
var fs = require('fs')
var path = require('path')

module.exports = function(directory, extension, callback) {

    fs.readdir(directory, function (err, list) {
        if (err) {
            callback(err);
        } else {
            var result = [];
            list.forEach(function (file) {
                if (path.extname(file) === '.' + process.argv[3]) {
                    result.push(file);
                }
            });
            callback(null, result);
        }
    });
}
```

**Comment by aualdrich** [comment]
@rvagg I think the hang-up is that the error isn't consistent with what's actually going on. Could you make it a bit more clear? Thanks!

**Comment by dartinez** [comment]
This was where I really hit a brick wall for learning node.js. I suggest spending no more than an hour on it before looking at the solutions in rvagg's repository. It's best to spend more time reviewing the good code and trying to rewrite it from memory after analyzing it carefully, in my opinion.

**Comment by rabdill** [comment]
I'm pretty sure I agree with @dartinez -- I understood the whole "callback" flow from the [great link](https://github.com/maxogden/art-of-node#callbacks) in the instructions, but this bit, from the instructions, meant absolutely nothing to me:

```
    function bar (callback) {
      foo(function (err, data) {
        if (err)
          return callback(err) // early return
    
        // ... no error, continue doing cool things with `data`
    
        // all went well, call callback with `null` for the error argument
    
        callback(null, data)
      })
    }
```

I'll admit that I looked at the solution file after about 90 minutes of my brain melting into itself trying to figure out where these callbacks were supposed to be pointing, and once I saw the full example I finally understood which functions were supposed to take arguments and which were supposed to just receive `(err, data)`. I think my block in this one was that the instructions just assume a little too much comfort with the callbacks before chucking them into modules.
