### ISSUE TITLE
HTTP File Server notes reference a previously unmentioned variable

### ISSUE THREAD

**Issue by JamesGould123** [workshopper/learnyounode#144]
[The HTTP File Server notes can be seen here for reference.](https://gist.github.com/JamesGould123/8d61ee10b69d2eca429f)

In the final paragraph of the HTTP File Server notes, the `src` and `dst` variables are referenced, which are previously unmentioned. It can be logically deduced that the `src` variable is the return object from fs.createReadStream(). However, in the previous example, the variable that is now referred to as `dst` was referred to as `res`. The unexplained name change was quite confusing.

> > var http = require('http')
> >     var server = http.createServer(function (req, res) {
> >       // request handling logic...
> >     })
> >     server.listen(8000)

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
