### ISSUE TITLE
Make it modular answer not accepted

### ISSUE THREAD

**Issue by Kipke** [workshopper/learnyounode#149]
In the makeitmodular exercise I have 2 files makeitmodular.js, which looks like this:

``` javascript
var mymodule = require('./makeitmodularmodule.js');

mymodule(process.argv[2], process.argv[3], function(err,res){
    if(err)
        return console.error('error: ',err);
    for (var i = 0; i < res.length; i++) {
        console.log(res[i]);
    };
});
```

and a module called makeitmodularmodule.js, which looks like this:

``` javascript
var fs = require('fs');
var path = require('path');

module.exports = function(dir,ext,callback){
    fs.readdir(dir,function(err,list){
        if(err)
            return callback(err);

        list = list.filter(function(obj){
            return path.extname(obj) === '.' + ext;
        })  

        return callback(null,list);
    })
}
```

That gives me the correct answer, however verify does not accept it saying: "Did not use an additional module file, you must require() a module to help solve this exercise".

I suppose this is a bug since I am definitely using my module to solve the problem.

Hope you guys can do something with this.

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
