### ISSUE TITLE
Unable to install with npm

### ISSUE THREAD

**Issue by x-tropy** [workshopper/learnyounode#165]
npm install learnyounode -g

npm http GET https://registry.npmjs.org/learnyounode
npm http 200 https://registry.npmjs.org/learnyounode
npm http GET https://registry.npmjs.org/learnyounode/-/learnyounode-1.0.6.tgz
npm http 200 https://registry.npmjs.org/learnyounode/-/learnyounode-1.0.6.tgz
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/learnyounode'
npm ERR! error rolling back  learnyounode@1.0.6 { [Error: EACCES, unlink '/usr/local/lib/node_modules/learnyounode']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/learnyounode' }
npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/learnyounode'
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/learnyounode']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/learnyounode' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "learnyounode" "-g"
npm ERR! cwd /Users/Rio/workspace/nodejs
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /usr/local/lib/node_modules/learnyounode
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/local/lib/node_modules/learnyounode'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/Rio/workspace/nodejs/npm-debug.log
npm ERR! not ok code 0

**Comment by johan718** [comment]
@julianduque I also had the same issue. Is this normal behavior when installing learnyounode on a clean install of node v4.2.3, or is my install broken somehow?

**Comment by johan718** [comment]
@julianduque I also had the same issue. Is this normal behavior when installing learnyounode on a clean install of node v4.2.3 and nmp 3.5.1 or is my install broken somehow.

**Comment by martinheidegger** [comment]
@johan718 This behaviour is not related to learnyounode. `npm install -g ...` tells nodejs to install something in a _global_ location. The node.js mac installer installs itself in a way that the global folder is shared with other users and can only be written by a super-user (good practice imho.). Thats why you need to add `sudo` in front of the command.

**Comment by johan718** [comment]
@martinheidegger thanks a lot. Makes sense...
