### ISSUE TITLE
Possible change to MYFIRSTIO

### ISSUE THREAD

**Issue by mdouglasbrett** [workshopper/learnyounode#190]
Hi guys/gals, 

I posted the following over at the Node School discussion thread, @martinheidegger suggested I re-post here:

> Hi guys!
> 
> I'm a big fan of your program. Just wanted to raise something. The following code, passes the verifier:
> 
>    var fs = require('fs');
>     var buff = fs.readFileSync( '/Users/michaelbrett/learnyounode/myfirstio.js' );
>     var str = buff.toString();
>     var arr = str.split('\n');
> 
>   console.log(arr.length);
> 
> But after seeing the actual solution, I realised I had missed the point of using process.argv. In this case, I hadn't truly fulfilled the aim of the exercise - Is it too picky to make the exercise demand the use of process.argv to be successful?
> 
> Just a thought.
> 
> Keep up the good work!
> 
> Mike

It was also suggested I might do a pull request, but I only have a small clue as to where to start (although I am willing to get my hands dirty).

Thanks for reading, perhaps I will see you in chat over the next couple of days.

Mike

**Comment by rvagg** [comment]
we probably need to run the checker against multiple files of different sizes to make sure it's doing the right thing, that would indirectly test everything we need.
