### ISSUE TITLE
Can't launch verify on Time Server

### ISSUE THREAD

**Issue by bengentil** [workshopper/learnyounode#2]
For the Time Server, the verify command fail to launch, I get connection refused.

No other TCP server is running on 8000 or 8001. 
The run command is running correctly and I get the date.

If I run my solution directly, I can get the date with a telnet.

Here the full output when I launch verify:

```
ACTUAL                             EXPECTED
------                             --------

events.js:77
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:671:11)
    at Object.afterConnect [as oncomplete] (net.js:938:19)
```

And my solution:

```
var net = require('net')

function zeroFill(number) {
    return (number < 10 ? '0'+number : number)
}

var server = net.createServer(function (socket) {
    var date=new Date()
    var strDate=date.getFullYear()+'-'+
                zeroPad(date.getMonth())+'-'+
                zeroPad(date.getDay())+' '+
                zeroPad(date.getHours())+':'+
                zeroPad(date.getMinutes())+'\n'
    socket.write(strDate)
    socket.end()
})
server.listen(8000)

```

**Comment by HarshaKasturi** [comment]
It worked for me, I used **strftime** as specified in the hints. This is my code,

var net = require('net'),
	strftime = require('strftime');
	
var port = process.argv[2];

var server = net.createServer(function (socket) {
  socket.end(strftime("%F %R") + "\n");  
})
server.listen(port);
