### ISSUE TITLE
HTTP UPPERCASERER passes but takes minutes to complete

### ISSUE THREAD

**Issue by StevenKitzes** [workshopper/learnyounode#228]
I passed this challenge, but saw unexpected behavior.  When I ran verify, all lines matched 'actual' to 'expected' but it would hang after.  I force quit thinking I made a mistake.

I tried some changes, still got matching output but still hanging.  While I went to web search for ideas, I left the verify process hanging.  When I returned over a minute later it had finally passed.

Is this expected behavior?  If so, maybe a warning is warranted for those running this tutorial who don't know it's normal to see the verify hang for so long!

If this is not expected, what might I have done wrong, or what might be wrong with my setup/web settings/etc?

**Comment by rvagg** [comment]
no, not expected, can we have a look at your code and can you tell us about your operating system and version of Node?

**Comment by StevenKitzes** [comment]
Sure thing.  I'm on Win8.1 on a newer ThinkPad.  Node is v0.12.0 off a fresh install.  Not sure if it matters, but I'm testing in Git Bash.  Though, I'm doing all the lessons in Git Bash with no other trouble.  The hang is consistent on this lesson.  Following is my code:

    var http = require('http');
    
    var server = http.createServer(httpHandler);
    
    server.listen(process.argv[2]);
    
    function httpHandler(req, rsp) {
    	if(req.method != 'POST') {
    		console.log('illegal request method');
    	}
    	else {
    		req.on('data', handlePostData(rsp));
    	}
    }
    
    function handlePostData(rsp) {
    	return function(data) {
    		var str = data.toString();
    		str = str.toUpperCase();
    		rsp.write(str);
    	};
    };

**Comment by StevenKitzes** [comment]
Also maybe worth noting that the 'actual' vs 'expected' analysis comes out quite promptly before I get the hang.

**Comment by victorpolko** [comment]
Hello there, @StevenKitzes!
I've ran into the same trouble a couple of minutes ago and found out that you forgot one small thing every server wants you to do: a response.end() callback. Try this:
```javascript
    ...
        console.log('illegal request method');
    }
    else {
        req.on('data', handlePostData(rsp));
        req.on('end', rsp.end())
    }
    ...
```

**Comment by rvagg** [comment]
yes, it's the missing `end()`, although the simplest way to do this is to simply swap `rsp.write(str);` for `rsp.end(str);` ..

I'd like to leave this issue open though because it points to the fact that we should put a shorter timeout on the request rather than letting it hang without providing feedback.

**Comment by victorpolko** [comment]
@rvagg, a little notice here: when you replace .write() with .end(), you only get first stream transmission, and the "Your solution to HTTP UPPERCASERER didn't pass. Try again!", because submission results will not match expected ones (except for the first string).

**Comment by rvagg** [comment]
oh right sorry, forgot the context of the problem,  ignore my advice then!

**Comment by StevenKitzes** [comment]
Ahh, thank you gentlemen!  Thought I might have missed something.

**Comment by Frank2016** [comment]
The hint in this exercise is misleading. You do not need "through2-map".
