### ISSUE TITLE
Stuck at "Filtered Ls" exercise

### ISSUE THREAD

**Issue by darnaud** [workshopper/learnyounode#263]
When I try to have my code verified I am shown the failed screen because my submission  results don't match. 
The funny thing is that the error comes from the fact that I have more files sharing the same extension than what is expected. Can you tell me what I am doing wrong?

Here are pictures of my code and submission results

![screen shot 2015-04-09 at 7 34 26 am](https://cloud.githubusercontent.com/assets/5556984/7066731/25232c04-de8b-11e4-919f-df15c901040b.png)

![screen shot 2015-04-09 at 7 34 44 am](https://cloud.githubusercontent.com/assets/5556984/7066742/345dc4a4-de8b-11e4-8fe6-62667a1d4053.png)

I found my mistake I didn't pay attention to the "one file per line" requirement. :/
Anyways is there a more elegant way to print each array element individually?
This is the code I used: 
![screen shot 2015-04-09 at 8 07 07 am](https://cloud.githubusercontent.com/assets/5556984/7067364/525e33b2-de90-11e4-9691-1b6af6d84786.png)

**Comment by grabbou** [comment]
Well, there's nothing wrong with your code. You could've always written `filtered.forEach(console.log)` but not sure if that is worth doing (less readable imo)

**Comment by julianduque** [comment]
@darnaud that forEach code is a very good approach, the approach proposed by @grabbou would not work becauce it will pass all the arguments of `forEach` and print something like:

```
> [ 'CHANGELOG.md', 'README.md', 'LICENCE.md' ].forEach(console.log)
CHANGELOG.md 0 [ 'CHANGELOG.md', 'README.md', 'LICENCE.md' ]
README.md 1 [ 'CHANGELOG.md', 'README.md', 'LICENCE.md' ]
LICENCE.md 2 [ 'CHANGELOG.md', 'README.md', 'LICENCE.md' ]
```
