### ISSUE TITLE
Allow reverse for loops

### ISSUE THREAD

**Issue by jesgundy** [workshopper/learnyounode#265]
Some of the tests (at least #5 - Filtered LS) expect a for loop, but don't expect a potential reverse for loop. So if items aren't printed in the right order, the result is not correct:

![](http://cl.ly/image/0z353M121319/Image%202015-04-10%20at%201.28.26%20PM.png)

**Comment by martinheidegger** [comment]
Two ways to solve it: 1) Make the check inverse-safe (a bit hard to do) 2) Write in the documentation that is should be in the same order as received (harder on the student).

**Comment by jesgundy** [comment]
I'd go with #2. Technically It's already a hardship on the student. I'm just suggesting we surface that information so it's less confusing when they encounter it. 

Or maybe the best course of action is nothing. Obviously I figured it out. My goal was just to surface a friction point I experienced - for your consideration. Thanks!
