### ISSUE TITLE
HTTP json server Parse Error: var data = _data.toString() undefined.

### ISSUE THREAD

**Issue by petercz1** [workshopper/learnyounode#295]
Ok, my json server appears to spit out the correct json for parsetime and unix time. However when I try to verify I get the following error:

Error connecting to http://localhost:44657/api/parsetime?iso=2015-05-23T10:36:00.242Z: Parse Error
/home/pc/.nvm/versions/node/v0.12.3/lib/node_modules/learnyounode/exercises/http_json_api_server/exercise.js:76
        var data = _data.toString()

When I fire up my server on port 44657 and manually curl this address it works. What gives? I presume I'm being a muppet somewhere along the line...

 curl http://localhost:44657/api/parsetime?iso=2015-05-23T10:36:00.242Z
{"hour":18,"minute":36,"second":0}

Full error:

pc@samsung:~/.../nodeschool/learnyounode$ learnyounode verify jsonServer.js
✗ Error connecting to http://localhost:44657/api/parsetime?iso=2015-05-23T10:36:00.242Z: Parse Error
/home/pc/.nvm/versions/node/v0.12.3/lib/node_modules/learnyounode/exercises/http_json_api_server/exercise.js:75
        var data = _data.toString()
                        ^
TypeError: Cannot read property 'toString' of undefined
    at BufferList.onData [as _callback] (/home/pc/.nvm/versions/node/v0.12.3/lib/node_modules/learnyounode/exercises/http_json_api_server/exercise.js:75:25)
    at BufferList.<anonymous> (/home/pc/.nvm/versions/node/v0.12.3/lib/node_modules/learnyounode/node_modules/bl/bl.js:16:14)
    at DestroyableTransform.emit (events.js:107:17)
    at ClientRequest.<anonymous> (/home/pc/.nvm/versions/node/v0.12.3/lib/node_modules/learnyounode/node_modules/hyperquest/index.js:13:19)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketOnData (_http_client.js:322:9)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)

**Comment by marocchino** [comment]
Did you implement `/api/unixtime` part?

**Comment by petercz1** [comment]
Yes, /api/unixtime is implemented and seems to work:

curl 127.0.0.1:3000/api/unixtime?iso=2013-08-10T12:10:15.474Z
{"unixtime":1376136615474}

Also, I'm running node 0.12.3 via nvm - dunno if this matters?

**Comment by marocchino** [comment]
um... It possible but, I don't think so.
Did you sending empty data? It could be matter in this [code](https://github.com/workshopper/learnyounode/blob/master/exercises/http_json_api_server/exercise.js#L71-L75)

**Comment by marocchino** [comment]
Can I see your code?

**Comment by petercz1** [comment]
Latest version:

var http = require('http');
var port = process.argv[2];
var url = require('url');

var server = http.createServer(sort_routes_out);
server.listen(port);

function sort_routes_out(req, res) {
    var urlRequest = url.parse(req.url, true);
    var date = new Date(urlRequest.query.iso);

    if (urlRequest.pathname == '/api/parsetime') {
        result = parsetime(date);
    }
    else if (urlRequest.pathname == '/api/unixtime') {
        result = unixtime(date);
    }

    res.writeHead(200, {'content=Type': 'application/json'});
    res.end(JSON.stringify(result));
}
;

function parsetime(date) {
    return {
        hour: date.getHours(),
        minute: date.getMinutes(),
        second: date.getSeconds()
    };
}
;

function unixtime(date) {
    return {
        unixtime: date.getTime()
    };
}
;

**Comment by marocchino** [comment]
It was typo in head.
```diff
-res.writeHead(200, {'content=Type': 'application/json'});
+res.writeHead(200, {'Content-Type': 'application/json'});
```

**Comment by petercz1** [comment]
Woo Hoo!!! Excellent piece of detective work - thank you!

I wonder should learnyounode>verify have picked that up?
