### ISSUE TITLE
Regression test harness

### ISSUE THREAD

**Issue by eeeschwartz** [workshopper/learnyounode#30]
I'm interested in adding a simple test harness to guard against regressions as alluded to in [a recent PR](https://github.com/rvagg/learnyounode/pull/28#discussion_r6693318). 

I can't imagine it's too difficult since workshopper is essentially a test framework already.

Would this work be useful to the project in your collective minds?

**Comment by martinheidegger** [comment]
As part of the translation efforts I added a set of tests to `learnyounode` https://github.com/rvagg/learnyounode/tree/master/test/

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
