### ISSUE TITLE
typo in last exercise

### ISSUE THREAD

**Issue by dkegle** [workshopper/learnyounode#302]
Last sentence of instructions for last exercise should be: "Date.getTime() will also come in handy." instead of "Date#getTime() will also come in handy."

Cheerz!

**Comment by tomhanlon** [comment]
Hey @dkegle,

This is actually present throughout the hints/instructions and from what I can tell from [this Stackoverflow post](http://stackoverflow.com/questions/736120/why-are-methods-in-ruby-documentation-preceded-by-a-hash-sign) seems to be an old convention that some people apply when referring to JS methods. It's also used in Ruby, for what that's worth.

This one's probably a non-issue. 

Tom

**Comment by SomeoneWeird** [comment]
Agreed, I don't think this is an issue.
