### ISSUE TITLE
"First Async IO" not returning string w/'/n'

### ISSUE THREAD

**Issue by Chrinkus** [workshopper/learnyounode#304]
When I log data w/o 'utf8' it returns a buffer file as expected. With 'utf8' it returns a ton of text however the text does not contain '/n'.

Code:

var fs = require('fs');

fs.readFile(process.argv[2], 'utf8', function logLines(err, data) {
  console.log(data.split('/n').length - 1);
})

**Comment by tgfjt** [comment]
Allrught, try `\n`:D

**Comment by Chrinkus** [comment]
are you kidding me?! i stared at this code for an hour. being new sucks.
