### ISSUE TITLE
i can't see parenthesis

### ISSUE THREAD

**Issue by italoacasas** [workshopper/learnyounode#312]
Hi guys, this is normal?

![screen shot 2015-06-10 at 12 53 15 am](https://cloud.githubusercontent.com/assets/6354455/8075200/5ca3140e-0f0b-11e5-817e-3f4b4fb7c4c0.png)

**Comment by tgfjt** [comment]
I guess it related: #96

**Comment by italoacasas** [comment]
Ups, sorry..
