### ISSUE TITLE
Error messages doesn't respect the defined language

### ISSUE THREAD

**Issue by montogeek** [workshopper/learnyounode#320]
Hi!

After changing the language to Spanish and verify a wrong submission the error messages are still appearing in English. 
![screen shot 2015-06-24 at 18 26 54](https://cloud.githubusercontent.com/assets/1002461/8343766/9cb0f87e-1a9e-11e5-8908-4de09598a35d.png)

**Comment by tgfjt** [comment]
I think it will be fixed when new version of learnyounode is published. :)

cc: @julianduque @martinheidegger

**Comment by montogeek** [comment]
I will work on it :)

**Comment by julianduque** [comment]
learnyounode@2.7.0 published, @montogeek can you confirm if still happening?

**Comment by montogeek** [comment]
It's solved in the latest version (2.7.0).
