### ISSUE TITLE
Spelling mistakes

### ISSUE THREAD

**Issue by xxlv** [workshopper/learnyounode#326]
when i selected chinese language and i run 'learnyounode verify myfile.js', and it give me a string contain “reqiure()” ,it should be require()

**Comment by julianduque** [comment]
@xxlv can you share a screenshot of this please?

**Comment by tgfjt** [comment]
I found out it on `i18n/zh-cn.json`.
https://github.com/workshopper/learnyounode/pull/327

**Comment by julianduque** [comment]
awesome! it was published on learnyounode@2.7.1
