### ISSUE TITLE
Baby Steps: 'learnyounode run program.js 1 2 3' returns different (and random) results than 'node program.js 1 2 3'

### ISSUE THREAD

**Issue by mattme** [workshopper/learnyounode#330]
I wrote the following solution to the Baby Steps lesson:
```javascript
var processArguments = process.argv;
var arrayLength = processArguments.length;
var total = 0;
for (var i = 2; i < arrayLength; i++) {
  var convertedIntoNumber = Number(processArguments[i]);
  var total = total + convertedIntoNumber;
}
console.log(total)
```
When I run `node program.js 1 2 3` I get the expected result: 6

When I do run `learnyounode run program.js 1 2 3` I don't get the expected result but always some random number. The last three times I ran this command the results were 100, 208 and 50. Why is that?

**Comment by CarlosRen** [comment]
I have similar question with you in my code 
``` console.log(process.argv[2]) ```
if i run ``` node app.js  3 4 5 ``` I get expected result:3 but if I execute ``` learnyounode run app.js ```  shows 47

**Comment by jcsayre** [comment]
Same issue here.
Running Windows 7 Home Premium 64-bit SP1
Using Powershell 1.0

<code> node program.js 1 2 3 </code>  result is consistently 6
<code> learnyounode program.js 1 2 3 </code> result is not predictable and varies from one execution to the next. 

see below for execution and my version of the code (which included some console debugging to help me figure out if I was doing something wrong).

Execution output for <code>node program.js 1 2 3</code> is below.
<code>
PS C:\Users\jcsayre\AppData\Roaming\npm\node_modules\learnyounode> node program.js 1 2 3
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\jcsayre\\AppData\\Roaming\\npm\\node_modules\\learnyounode\\program.js',
  '1',
  '2',
  '3' ]
6
PS C:\Users\jcsayre\AppData\Roaming\npm\node_modules\learnyounode> node program.js 1 2 3
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\jcsayre\\AppData\\Roaming\\npm\\node_modules\\learnyounode\\program.js',
  '1',
  '2',
  '3' ]
6
PS C:\Users\jcsayre\AppData\Roaming\npm\node_modules\learnyounode> node program.js 1 2 3
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\jcsayre\\AppData\\Roaming\\npm\\node_modules\\learnyounode\\program.js',
  '1',
  '2',
  '3' ]
6
PS C:\Users\jcsayre\AppData\Roaming\npm\node_modules\learnyounode> </code>

Output for <code>learnyounode run program.js 1 2 3</code> is below.
<code>
PS C:\Users\jcsayre\AppData\Roaming\npm\node_modules\learnyounode> learnyounode run program.js 1 2 3
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\jcsayre\\AppData\\Roaming\\npm\\node_modules\\learnyounode\\program.js',
  '68',
  '46',
  '8' ]
122
PS C:\Users\jcsayre\AppData\Roaming\npm\node_modules\learnyounode> learnyounode run program.js 1 2 3
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\jcsayre\\AppData\\Roaming\\npm\\node_modules\\learnyounode\\program.js',
  '64',
  '84' ]
148
PS C:\Users\jcsayre\AppData\Roaming\npm\node_modules\learnyounode> learnyounode run program.js 1 2 3
[ 'C:\\Program Files\\nodejs\\node.exe',
  'C:\\Users\\jcsayre\\AppData\\Roaming\\npm\\node_modules\\learnyounode\\program.js',
  '1',
  '60',
  '93',
  '58',
  '36',
  '15' ]
263
PS C:\Users\jcsayre\AppData\Roaming\npm\node_modules\learnyounode>
</code>

My version of the program:
<code>
var result = 0;
console.log(process.argv);
for (i = 2; i < process.argv.length; i++)
	result += Number(process.argv[i]);
console.log(result);
</code>

**Comment by gorhgorh** [comment]
Hello, this is normal, when you use the run or the test command from learnyounode it generates RANDOM arguments to test your solution to the problem, as you have seen in the log of 'process.argv'.
run command does not only run your solution, it provides it the context and data needed for it.

**Comment by mattme** [comment]
Ok. Thanks for your explanation. But then I don't get why in the "hints" section of this lesson it says:
 > learnyounode will be supplying arguments to your program when you run `learnyounode verify program.js` so you don't need to supply them yourself. To test your program without verifying it, you can invoke it with `learnyounode run program.js`. When you use run, you are invoking the test environment that learnyounode sets up for each exercise.

I'm confused. Am I supposed to test my exercises with `node file.js` or `learnyounode run file.js`?
