### ISSUE TITLE
Issues with workshopper on Ukrainian

### ISSUE THREAD

**Issue by denysdovhan** [workshopper/learnyounode#331]
I've translated _learnyounode_ and _workshopper_ on Ukrainian, but when I choose Ukrainian from menu, I get:

![2015-07-09 12 04 54](https://cloud.githubusercontent.com/assets/3459374/8591797/5160354c-2633-11e5-8db3-11e46743017d.png)

So, I think the problem is that _learnyounode_ just uses old _workshopper_'s version.

**Comment by denysdovhan** [comment]
Yes, this is it. I look at global `learnyounode/node_modules/workshopper/i18n` and there is no `uk.json` file, even after updating:

![2015-07-09 12 16 00](https://cloud.githubusercontent.com/assets/3459374/8591992/a81c05b8-2634-11e5-8d78-12de33b2c7ef.png)

**Comment by tgfjt** [comment]
Uh workshopper/workshopper need to be published...

**Comment by denysdovhan** [comment]
@tgfjt please, update it, 'cause many people are waiting for this.

**Comment by julianduque** [comment]
This was published on learnyounode@2.7.1, can you confir if still happening?

**Comment by denysdovhan** [comment]
Yep, works fine. Thanks, guys :+1:

**Comment by tgfjt** [comment]
:blush::+1:
