### ISSUE TITLE
Learnyounode must be global?

### ISSUE THREAD

**Issue by cataquil** [workshopper/learnyounode#332]
Does learnyounode have to be install with the -g switch global.

Running it puts it in windows Users\AppData\Roaming\npm to run 'learnyounode'

need to write the 1st helloworld and want to keep it in my c:\node\learnyounode folder

**Comment by denysdovhan** [comment]
> Running it puts it in windows 

Did you add node and npm to PATH?

> need to write the 1st helloworld and want to keep it in my c:\node\learnyounode folder

You can install learnyounode into any folder, and run it from this folder as:

```
node learnyounode.js
```

**Comment by mw8020** [comment]
Way ongoing less keystrokes just installing it globally. You can then always `npm uninstall learnyounode -g` once you're done.

**Comment by martinheidegger** [comment]
It is also possible to install learnyounode locally: run `npm i learnyounode` in a folder (none of the parent folders should have a package.json) and then it will be installed in the `node_modules` folder. You can start learnyounode in this setup with:

`./node_modules/.bin/learnyounode` in that case.
