### ISSUE TITLE
weird process.argv

### ISSUE THREAD

**Issue by cuciferus** [workshopper/learnyounode#354]
I'm trying out the baby steps on my linux machine but I've found out that running my program with
learnyoucode run doi.js 2 3, where doi.js is now just console.log(process.argv), outputs: 
[ '/usr/x86_64-pc-linux-gnu/bin/node',
  '/home/luser/prostii/learnyoucode/doi.js',
  '15',
  '59',
  '82' ]
but running it node doi.js gives me the corect ouput:
[ 'node',
  '/home/luser/prostii/learnyoucode/doi.js',
  '2',
  '3' ]

**Comment by julianduque** [comment]
@cuciferus when using `learnyounode run` it will pass some random test values (the same used in verify), this is why you are getting those numbers instead of what you are providing as arguments.
