### ISSUE TITLE
HTTP FILE SERVER: no open event for createReadStream?

### ISSUE THREAD

**Issue by ggiraffe** [workshopper/learnyounode#362]
Hi! In Exercise 11 HTTP FILE SERVER, the official solution calls `pipe()` directly following `fs.createReadStream()`. I don't find in Nodejs api manual telling not to do in this way, but it says "Emitted when the ReadStream's file is opened." under "Event: 'open'". So, is it more proper or no difference of listening to the open event?

Official answer:
```javascript
fs.createReadStream(process.argv[3]).pipe(res)
```
My solution:
```javascript
var rs = fs.createReadStream(process.argv[3]);
rs.on('open', function() { rs.pipe(res); });
```

Can anyone explain this to me? Thanks in advance.

**Comment by ralphtheninja** [comment]
There is no need in waiting for the open event since node handles this for us. The `'open'` is there for you to react on, so you could do something like:

```js
var rs = fs.createReadStream(process.argv[3])
rs.on('open', function() { console.log('the file was opened') })
rs.pipe(res)
```

**Comment by ggiraffe** [comment]
Thanks for your quick res!
