### ISSUE TITLE
Issue related to "Make it Modular"

### ISSUE THREAD

**Issue by jinxac** [workshopper/learnyounode#367]
Following is my "program.js"

         var mymodule=require('./module.js');
         var print=function(error,data){

         if(error===null){
                    console.log(data);
              }
         else
              {
            console.log(error);
                 }
          }
        mymodule(process.argv[2],"."+process.argv[3],print);

And following is my "module.js"

                      var fs=require('fs');
                      var filter=require('path');

                    module.exports=function(directoryName,FilterName,callback)
                   {
                           fs.readdir(directoryName,function done(err,data){
                         if(err){return callback(err,null);}
                         else
                        {
                                  for(var i=0;i<data.length;++i)
                            {
                                        var extension=filter.extname(data[i]);
                                       if(extension === FilterName){
                                        callback(null,data[i]);
                             }
                              }
                            } 
                               })
                             } 

I am getting following error "Your additional module file [module.js] did not call the callback argument
# FAIL"

Is this an issue or I am doing something wrong? I am new to this so can someone please help me?

**Comment by phecht** [comment]
Here is my solution for the lazy:
program6.js:
var filter = require('./module6.js');

// Un-comment below to demonstrate usage, which seems to be fine and *should* pass(?)
filter(process.argv[2], process.argv[3], function(err, data) {
if (err) {
        console.log(err);
        }
//
data.forEach(function(item) {
console.log(item);
 });
});

more module6.js 
var fs = require('fs');
var path = require('path');

module.exports = function(dir, ext, callback) {
         fs.readdir(dir, function(err, files) {
                 var pass = [];

                 if (err) {
                         return callback(err);
                 }
                 files.forEach(function(file) {
                         if (path.extname(file) === '.' + ext) {
                                 pass.push(file);
                         }
                 });
                 return callback(null, pass);
         });
};

I found this on another site.  They almost had it.  I just put the parameters in program6.js and it passed.

**Comment by martinheidegger** [comment]
I assume its resolved please open if you still have a problem.
