### ISSUE TITLE
"TypeError: Cannot read property 'call' of undefined" after changing language and entering any exercise

### ISSUE THREAD

**Issue by lucasfcosta** [workshopper/learnyounode#373]
How to reproduce:
1 - Run learnyounode
2 - Choose any language
3 - Enter any of the exercises

Does this happens to anyone else?

EDIT: Actually it seems to be an workshopper issue

**Comment by lucasfcosta** [comment]
An workshopper issue indeed.

**Comment by martinheidegger** [comment]
It is not an workshopper issue, its an issue with terminal-menu and it should be fixed with this PR: https://github.com/workshopper/learnyounode/pull/368
