### ISSUE TITLE
npm ERR! code 1

### ISSUE THREAD

**Issue by superkresek** [workshopper/learnyounode#380]
i get this message when running command sudo npm install -g learnyounode

npm WARN install:chalk@1.1.1 ENOENT, rename '/usr/local/lib/node_modules/learnyounode/node_modules/@leichtgewicht/msee/node_modules/chalk'
- ansi-regex@2.0.0 node_modules/learnyounode/node_modules/@leichtgewicht/msee/node_modules/ansi-regex
- ansi-styles@2.1.0 node_modules/learnyounode/node_modules/@leichtgewicht/msee/node_modules/chalk/node_modules/ansi-styles
- has-ansi@2.0.0 node_modules/learnyounode/node_modules/@leichtgewicht/msee/node_modules/chalk/node_modules/has-ansi
- strip-ansi@3.0.0 node_modules/learnyounode/node_modules/@leichtgewicht/msee/node_modules/chalk/node_modules/strip-ansi
- supports-color@2.0.0 node_modules/learnyounode/node_modules/@leichtgewicht/msee/node_modules/chalk/node_modules/supports-color
- ansi-styles@2.1.0 node_modules/learnyounode/node_modules/eslint/node_modules/chalk/node_modules/ansi-styles
- has-ansi@2.0.0 node_modules/learnyounode/node_modules/eslint/node_modules/chalk/node_modules/has-ansi
- strip-ansi@3.0.0 node_modules/learnyounode/node_modules/eslint/node_modules/chalk/node_modules/strip-ansi
- supports-color@2.0.0 node_modules/learnyounode/node_modules/eslint/node_modules/chalk/node_modules/supports-color
- esprima-fb@12001.1.0-dev-harmony-fb node_modules/learnyounode/node_modules/esprima-fb
- hoek@2.16.3 node_modules/learnyounode/node_modules/explicit/node_modules/joi/node_modules/hoek
- isemail@1.2.0 node_modules/learnyounode/node_modules/explicit/node_modules/joi/node_modules/isemail
- topo@1.1.0 node_modules/learnyounode/node_modules/explicit/node_modules/joi/node_modules/topo
- duplexer2@0.0.2 node_modules/learnyounode/node_modules/hyperquest/node_modules/duplexer2
- ansi-styles@2.1.0 node_modules/learnyounode/node_modules/inquirer/node_modules/chalk/node_modules/ansi-styles
- has-ansi@2.0.0 node_modules/learnyounode/node_modules/inquirer/node_modules/chalk/node_modules/has-ansi
- supports-color@2.0.0 node_modules/learnyounode/node_modules/inquirer/node_modules/chalk/node_modules/supports-color
chalk@1.1.1 node_modules/learnyounode/node_modules/@leichtgewicht/msee/node_modules/chalk -> node_modules/learnyounode/node_modules/msee-preview/node_modules/chalk
- ansi-styles@2.1.0 node_modules/learnyounode/node_modules/no-shadow-relaxed/node_modules/chalk/node_modules/ansi-styles
- has-ansi@2.0.0 node_modules/learnyounode/node_modules/no-shadow-relaxed/node_modules/chalk/node_modules/has-ansi
- strip-ansi@3.0.0 node_modules/learnyounode/node_modules/no-shadow-relaxed/node_modules/chalk/node_modules/strip-ansi
- supports-color@2.0.0 node_modules/learnyounode/node_modules/no-shadow-relaxed/node_modules/chalk/node_modules/supports-color
- espree@2.2.5 node_modules/learnyounode/node_modules/no-shadow-relaxed/node_modules/espree
- rx@2.5.3 node_modules/learnyounode/node_modules/no-shadow-relaxed/node_modules/inquirer/node_modules/rx
- ansi-styles@2.1.0 node_modules/learnyounode/node_modules/simple-terminal-menu/node_modules/chalk/node_modules/ansi-styles
- has-ansi@2.0.0 node_modules/learnyounode/node_modules/simple-terminal-menu/node_modules/chalk/node_modules/has-ansi
- strip-ansi@3.0.0 node_modules/learnyounode/node_modules/simple-terminal-menu/node_modules/chalk/node_modules/strip-ansi
- supports-color@2.0.0 node_modules/learnyounode/node_modules/simple-terminal-menu/node_modules/chalk/node_modules/supports-color
- @leichtgewicht/msee@0.3.1 node_modules/learnyounode/node_modules/@leichtgewicht/msee
- espree@2.2.5 node_modules/learnyounode/node_modules/eslint/node_modules/espree
- espree@2.2.5 node_modules/learnyounode/node_modules/lab/node_modules/espree
/usr/local/lib
└── (empty)

npm ERR! code 1

what happens? 
my npm version is 3.3.12
thank you.

**Comment by hnaoto** [comment]
This might have something to do with your npm version. My npm version is 2.14.7 and node version is v4.2.2.  They work fine, but 3 doesn't work.

**Comment by superkresek** [comment]
ohh this is my fault. i polute my node and npm instalation from multiple source. i can use learnyounode after updating all installed npm package.
