### ISSUE TITLE
MAKE IT MODULAR ERROR: There was a problem printing the solution files: testing

### ISSUE THREAD

**Issue by R4meau** [workshopper/learnyounode#395]
Hi guys, I need some help here, here's my code for this section of the tutorial:
Module (filteredls.js):
```js
module.exports = function(dir, ext, callback) {
	var fs = require("fs"),
		path = require("path");
		
	fs.readdir(dir, function(err, data) {
		if (err)
			callback(err);
		data = data.filter(function(file) {
			return path.extname(file) === '.' + ext;
		});
		callback(null, data);
	});
};
```

program (program.js):
```js
var filteredls = require("./filteredls");

filteredls(process.argv[2], process.argv[3], function(err, data) {
	if (err) console.log(err);
	data.map(function(x) {
		console.log(x);
	});
});
```

And here's the result of calling ```learnyounode verify program.js```:
<pre>Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "CHANGELOG.md"                      ==    "CHANGELOG.md"                     
   "LICENCE.md"                        ==    "LICENCE.md"                       
   "README.md"                         ==    "README.md"                        
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

ERROR: There was a problem printing the solution files: testing</pre>

node version: v0.12.7
npm version: 2.11.3
learnyounode version: 3.2.0

Please, let me know what I'm doing wrong. About to rip my hair at this.

**Comment by R4meau** [comment]
Okay, found my mistake, I had to ```return``` the callback function on line 7 in the module file, not just call it. So this:
```js
if (err)
    callback(err);
```
Becomes this:
```js
if (err)
    return callback(err);
```

**Comment by palmassi** [comment]
Why does the callback need to be returned in the error case but not the success case?

**Comment by vambo** [comment]
Because there execution should not continue when an error has occurred (without return it would).

The instruction also does state:
>  Also keep in mind that it is idiomatic to check for errors and do early-returns within callback functions:

**Comment by mplis** [comment]
I'm a little late here, but I was just wondering why the early-return syntax is preferred over omitting the return and doing an if/else statement?

Early-return:

    fs.readdir(dirname, function(err, list) {
        if (err) {
            return callback(err)
        }
        var files = list.filter(function (file) {
            return path.extname(file) === '.' + ext
        })
        callback(null, files)
    })

If/else:

    fs.readdir(dirname, function(err, list) {
        if (err) {
            callback(err)
        } else {
            var files = list.filter(function (file) {
                return path.extname(file) === '.' + ext
            })
            callback(null, files)
        }
    })

**Comment by zfields** [comment]
Is it possible for a test to capture this scenario and offer a good error message? Or perhaps a HINT reminding people that `callback(null, files);` is the same as `return callback(null, files);` as the last line of the function, but they are very different elsewhere in the function.
