### ISSUE TITLE
Exercise 10 (Time Server) - Newline in url 'https://github.com/samsonjs/strftime'

### ISSUE THREAD

**Issue by vboufleur** [workshopper/learnyounode#396]
There's a newline in the url 'https://github.com/samsonjs/strftime', making it point to the wrong URL. This URL is in the 10th exercise explanation text.

Expected:
> https://github.com/samsonjs/strftime

Actual: 
> https://github.com/samsonjs/strftim
> e

![captura de tela de 2015-12-28 01-18-22](https://cloud.githubusercontent.com/assets/16310611/12013578/ea554e28-ad00-11e5-8826-03b071d1f345.png)

**Comment by jpdamon** [comment]
This seems to just be a consequence of the word wrapping in the console. The problem.md file does not have a newline in there.
