### ISSUE TITLE
My First IO Should Not Subtract One from Number of Lines

### ISSUE THREAD

**Issue by caffeinewriter** [workshopper/learnyounode#410]
I was going through this with a friend, and we noticed that the subtract one does _not_ give the correct answer when there is no newline at the end of the file. It would be proper if there _was_ a newline at the end of the file, but it's incorrect otherwise.

Ex:

**File:**
```
This
Is
A
Seven
Line
Test
File
```

**Code:**
```javascript
var fs = require('fs');
var lines = fs.readFileSync(process.argv[2])
                .toString()
                .split("\n")
                .length - 1;
console.log(lines); // Returns 6;
```

However, if the file did have a newline at the end:

**File:**
```
This
Is
A
Seven
Line
Test
File

```

Then it would return 7, as expected.

This is also an issue in My First Async IO

**Comment by jjpenney** [comment]
The question actaully asks you to count the instances of '\n', not the number of lines in the file. Since the last line doesn't have a '\n', the count of '\n' is one less than the count of items in the array, when split. That's why you need to -1.

**Comment by caffeinewriter** [comment]
Ahh, my apologies.I misread that. Thanks for the response :+1:
