### ISSUE TITLE
[Windows] [Node 5.7.1] Can't move up/down arrows 

### ISSUE THREAD

**Issue by bartoszbinda** [workshopper/learnyounode#420]
I can't control menu during learnyou node. I can't move or nothing, I can just click enter.

**Comment by sinbargit** [comment]
I have the same situation

**Comment by MystK** [comment]
The solution is to use Git Bash

**Comment by rezja88** [comment]
Chrome.com

**Comment by rezja88** [comment]
Google

**Comment by rocifier** [comment]
I tried git bash and it says I must use a TTY compatible console. Also tried windows powershell and cmd, both of which dont allow arrow keys to work.

**Comment by martinheidegger** [comment]
This is a known bug of Node.js . https://github.com/nodejs/node/issues/5384 It is actively worked on. Unfortunately it affects a broad range of Node.js versions.
