### ISSUE TITLE
Is there a debug option in Learnyounode?

### ISSUE THREAD

**Issue by Hillsie** [workshopper/learnyounode#427]
Is there anyway of using the node debugger within Learnyounode?

**Comment by martinheidegger** [comment]
In which way? Do you want to debug learnyounode or your code?

**Comment by Hillsie** [comment]
@martinheidegger what I mean is there a similar way to perform something similar to
`node debug mycode.js`
for instance:
`learnyounode debug run mycode.js`

**Comment by martinheidegger** [comment]
It is not "officially supported" (quite a bit of work) but this works by running this in bash:

`node debug $(which learnyounode) run mycode.js`

**Comment by Hillsie** [comment]
thanks. will try it.
