### ISSUE TITLE
nodejs and npm issue

### ISSUE THREAD

**Issue by swathikrishnaguru** [workshopper/learnyounode#438]
The commands end with the below error.

-bash-4.1# bin/ldf-server config.json 8900 4
Master 57066 running.
module.js:442
    throw err;
    ^

Error: Cannot find module 'jsonld'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/RML-Mapper/Server.js/lib/writers/JsonLdWriter.js:5:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
module.js:442

After I tried to install jsonld which throws the error as below.

npm install jsonld 

make: Leaving directory `/opt/RML-Mapper/Server.js/node_modules/contextify/build'
gyp ERR! build error
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 2.6.32-431.20.3.el6.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/RML-Mapper/Server.js/node_modules/contextify
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm ERR! Linux 2.6.32-431.20.3.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "jsonld"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/RML-Mapper/Server.js/npm-debug.log

**Comment by martinheidegger** [comment]
This does not seem to be a `learnyounode` issue. Please reopen this issue in issues you have while learning node at https://github.com/nodeschool/discussions/issues, Issues while working with Node on https://github.com/nodejs/help/issues, issues with NPM at https://github.com/npm/npm/issues and in this case it maybe https://www.npmjs.com/package/contextify.
