### ISSUE TITLE
Why does console.log work with no arguments for http_client "best answer?"

### ISSUE THREAD

**Issue by caboosesw** [workshopper/learnyounode#446]
```javascript
res.on('data', console.log)
```

I can't intuitively figure this out or find any reference to why this would "know" to output something from a buffer.

https://nodejs.org/api/console.html#console_console_log_data

Thoughts?

I got my code working by explictly referencing the buffer like so ...

```javascript
res.on('data', function(chunk) {
    console.log(chunk);
});
```

**Comment by timoxley** [comment]
* JavaScript has first class functions, meaning they can be passed around just like any other value. 
* In both cases you're passing a function as the second argument to the `on` function. 
* `console.log` is a function value, as is `function(){}`. 
* `function () { ... }` is not really special syntax. It simply creates a function value.
* The function value you're passing just happens to call console.log in its body.
* When the 'data' event is fired, the second argument to `on` is called. It's called with the data as the first argument. 
* So when the data event occurs in `on('data', console.log)`, the second argument, which happens to be the `console.log` function, is called with data as the first argument.

**Comment by caboosesw** [comment]
... it's the last line that I don't fully get ... and forgive me for my terms since I am an old school pascal / Foxpro developer ... but I would think (outside of something being implied or passed via $scope) ... that it would be console.log (data) so something is passed to the console.log function...?


I am more than  willing to read any docs or.links...appreciate your clear writing style!





On Thu, Jul 7, 2016 at 5:23 PM -0400, "Tim Oxley" <notifications@github.com> wrote:











JavaScript has first class functions, meaning they can be passed around just like any other value. 
In both cases you're passing a function as the second argument to the on function. 

console.log is a function value, as is function(){}. 

function () { ... } is not really special syntax. It simply creates a function value.
The function value you're passing just happens to call console.log in its body.
When the 'data' event is fired, the second argument to on is called. It's called with the data as the first argument. 
So when the data event occurs in on('data', console.log), the second argument, which happens to be the console.log function, is called with data as the first argument.

**Comment by caboosesw** [comment]
... hey ... look at me ... I think I figured out what @timoxley meant ...

In ...
https://nodejs.org/api/stream.html#stream_event_data

... this states ...

> The listener callback will be passed the chunk of data as a string if a default encoding has been specified for the stream using the readable.setEncoding() method; otherwise the data will be passed as a Buffer.

... so I guess this means when "console.log" is called the data event emitter sends along the converted string chunk ... and console.log takes that and outputs it to the console ... right?

**Comment by timoxley** [comment]
Correct! You're not calling `console.log` directly, that's why you don't give it any arguments. It might help to think of first-class functions as stored procedures. You're passing some stored procedure to the event emitter which executes the stored procedure whenever a data event occurs.

**Comment by caboosesw** [comment]
Yeah...I got that part pretty easily...it was that the emitter sent the data to the function that was unclear by default 

Thanks again
