### ISSUE TITLE
MY FIRST I/O submission results match expected #FAIL

### ISSUE THREAD

**Issue by bagrounds** [workshopper/learnyounode#448]
![screen shot 2016-07-10 at 7 10 03 pm](https://cloud.githubusercontent.com/assets/4107454/16718218/d477256a-46d2-11e6-9be5-ceeb841ab9e6.png)

It looks like the tests pass, but it tells me it fails.

**Comment by tschoffelen** [comment]
Can you share the code you have in `program3.js`?

**Comment by talihashi** [comment]
I've just ran into the same problem myself, here's the Node prompt:
![screenshot 18](https://cloud.githubusercontent.com/assets/15970917/16813092/58d2a2dc-48ed-11e6-981d-9abbf374a93e.png)

And my program.js code:
console.log(process.argv);
var totalSum = 0;
for (var i = 2; i < process.argv.length; i++) {
	totalSum += Number(process.argv[i]);
}
console.log(totalSum);

**Comment by tschoffelen** [comment]
@talihashi Could you try removing the first `console.log` statement (first line)? I think that might help fix this particular issues.

**Comment by talihashi** [comment]
@tschoffelen Thank you, that solved it for me!

**Comment by bagrounds** [comment]
@tschoffelen 
```
;(function () {
  'use strict'

  var childProcess = require('child_process')

  var file = process.argv[2]

  var result = childProcess.execSync('cat ' + file + ' | wc -l')

  console.log(result.toString().trim())
}) ()

```

**Comment by bagrounds** [comment]
Turns out the test program requires you to use the fs.readFileSync function, specifically.

The problem statement: 
> Write a program that uses a single synchronous filesystem operation to  
  read a file and print the number of newlines (\n) it contains to the  
  console (stdout), similar to running cat file | wc -l.  
  The full path to the file to read will be provided as the first  
  command-line argument (i.e., process.argv[2]). You do not need to make  
  your own test file. 

I guess it's arguable whether or not **"a single synchronous filesystem operation"** refers specifically to fs.readFileSync.

Is a filesystem operation defined as a function of the node module fs?

Does the child_process module's execSync function not perform a synchronous filesystem operation?

I don't know, but perhaps ambiguity could be reduced by either:

1) changing the statement "uses a single synchronous filesystem operation" to "uses fs.readFileSync

or 2) changing the test case to allow for any synchronous filesystem operation that accomplishes the required task.

Aside:
All of this applies to problem 4 as well. Using the child_process module's exec function does not satisfy the tests, but fs.readFile (obviously) does.
