### ISSUE TITLE
JUGGLING ASYNC, how do I know if the URLs have returned all of their contents ?

### ISSUE THREAD

**Issue by edwinharly** [workshopper/learnyounode#455]

**Comment by ThalysonR** [comment]
using response.on('end',function(){}
or response.pipe(bl(function(){}));

**Comment by martinheidegger** [comment]
@edwinharly I think @ThalysonR properly answered the question but this is a question about how to solve learnyounode and not a problem with how learnyounode functions. Please ask questions like this on https://github.com/nodeschool/discussions/issues This way we can keep this repository clean.
