### ISSUE TITLE
learnyounode doesn't install on windows 8

### ISSUE THREAD

**Issue by voltair7** [workshopper/learnyounode#460]
I'm using command 
```
npm install -g learnyounode
``` 
and it halts when it gets to " verb gentlyRm don't care about con"

NPM Version 3.10.3
NODE Version 6.4.0

**Comment by martinheidegger** [comment]
I am experiencing the same issue. Seems to be a problem of new versions of `npm`. It would be good to triage the `npm` version that causes that problem.

**Comment by martinheidegger** [comment]
I created an issue on NPM: https://github.com/npm/npm/issues/13722

**Comment by ridjis** [comment]
Same here. Can't even uninstall properly.

**Comment by kenanbalija** [comment]
Try online code editor like c9.io. It's good for simple exercises like these

**Comment by martinheidegger** [comment]
@ridjis @voltair7 The problem was my mistake. I published a new version that should be possible to be installed properly. @voltair7 @ridjis would you mind to try it again? If it breaks, would you mind to run it with `npm i learnyounode -g -f --verbose` and share your output log.

**Comment by ridjis** [comment]
@martinheidegger Installation works now :+1:

**Comment by martinheidegger** [comment]
@voltair7 @ridjis Thank you for your patience and @ridjis thank you for the verification.
