### ISSUE TITLE
learnyounode #10 time server

### ISSUE THREAD

**Issue by kenanbalija** [workshopper/learnyounode#461]
Here is my code:

```
const net = require("net");
var portNum = process.argv[2];
const server = net.createServer((socket) =>{
    var d= new Date();
    var year = d.getFullYear();
    var month = addZero(d.getMonth());
    var day = addZero(d.getDay());
    var hour = addZero(d.getHours());
    var minutes = addZero(d.getMinutes());


    socket.write(year+'-'+month+'-'+day+ ' '+ hour+':'+minutes);
    socket.end('\n');
}).on('error', (err)=>{
    throw err;
})

server.listen(portNum);

 function addZero(i) {
        if (i < 10) {
            i = "0" + i;
        }
        return i;
    }
```

The thing is when i verify it gives wrong date. I am newbie, trying to find an answer for a quite a bit time. 

> ```
>              ACTUAL                                 EXPECTED                
> ```
> 
> ────────────────────────────────────────────────────────────────────────────────
> 
>    "2016-07-04 19:26"                  !=    "2016-08-25 19:26"  
>    ""                                  ==    ""                                 
> 
> ────────────────────────────────────────────────────────────────────────────────

**Comment by brymacto** [comment]
Hey there,

There are two issues with this:

1. `getMonth()` returns a value starting with zero, so you must add 1 to it.
2. `getDay()` returns day of the week, not day of the month.  You'll want to use `getDate()` instead.
