### ISSUE TITLE
"learnyounode". 4th lesson

### ISSUE THREAD

**Issue by lsag** [workshopper/learnyounode#473]
Hello. just starting in node. I think there is an error the exercise "learnyounode". 4th lesson. 

in [https://github.com/workshopper/learnyounode/blob/master/exercises/my_first_async_io/solution/solution.js](https://github.com/workshopper/learnyounode/blob/master/exercises/my_first_async_io/solution/solution.js)

instead of 

``` javascript
var file = 'process.argv[2]';
```

should be 

``` javascript
var file = 'process.argv[1]';
```

**Comment by lsag** [comment]
proper formatting

**Comment by matthamil** [comment]
@lsag `process.arg[1]` will always be the location to the script itself. `process.arg[2]` refers to the argument `FOO` immediately passed after you run `node program.js FOO`.

**Comment by Flet** [comment]
Here is a simple script to show what is in the `process.argv` array: 

test.js:
```js
console.log(process.argv)
```

output:
```bash
node test.js 1 2 3
[ '/Users/Flet/.nvm/versions/node/v6.3.0/bin/node',
  '/Users/Flet/test.js',
  '1',
  '2',
  '3' ]
```

**Comment by lsag** [comment]
forgot about this post, sorry. Thanks for the answer
