### ISSUE TITLE
TypeError: __ is not a function

### ISSUE THREAD

**Issue by aurelkurtula** [workshopper/learnyounode#478]
I installed `learnyounode`. when I run it I get

```
/usr/local/lib/node_modules/learnyounode/node_modules/workshopper-adventure/lib/commands/menu.js:46
    title: __('title'),
           ^

TypeError: __ is not a function
```

I have node v6.7.0. 

What might be the problem?

**Comment by filipenevola** [comment]
Hi, same error here.

**Comment by martinheidegger** [comment]
@aurelkurtula @filipenevola I am on it. Looking for the problem: Would you mind to give me your npm/node/os/learnyounode version?

**Comment by aurelkurtula** [comment]
@martinheidegger thanks for the quick response, here are the info

node: v6.7.0
npm: 3.10.6
learnyounode: 3.5.6

if I need to upgrade anything, let me know

**Comment by aurelkurtula** [comment]
I'm on a mac version 10.11.6

**Comment by filipenevola** [comment]
Hi @martinheidegger, versions:
npm 3.10.7
node v4.0.0
learnyounode 3.5.6

**Comment by martinheidegger** [comment]
I just published `learnyounode 3.5.7` it should fix that problem. Sorry, for the problems and THANK YOU for letting me know.

**Comment by aurelkurtula** [comment]
@martinheidegger Fantastic job. Thanks for the help

**Comment by filipenevola** [comment]
Thanks @martinheidegger
