### ISSUE TITLE
async juggling

### ISSUE THREAD

**Issue by riv3n** [workshopper/learnyounode#480]
Hello All,

I need some guidance on what I am doing wrong. my arrays that are holding the response streams are empty. I tried using node-inspector but I'm not clear on how to use it effectively.

``````
'use strict';
const http = require('http');
let respArr = []; // array of responses
for (let i = 2; i < 5; i++) {
  getUrl(process.argv[i], i - 2, respArr);
}//end for

/*
parameters
url: url to perform the GET operation on
id: unique id for each url
respArr: responseArray. holds an array of response arrays
*/

function getUrl(url, id, respArr) {
 let arr = []; //holds response stream
  http.get(url, (res) => {
  res.setEncoding('utf8');
    res.on('data', (data) => {  
    arr.push(data);
  }).on('end', () => {
      //when the response is finished, assign the array to the responseArray by id
      respArr[id] = arr;
  });//end 'end'
  });//end get
}```
``````

**Comment by martinheidegger** [comment]
Hello @riv3n Its awesome that you are working on learnyounode but this issue board is used for **bugs** or **features** in the workshopper. For help [nodeschool/discussions](https://github.com/nodeschool/discussions/issues) is a better place to post your question (and find solutions to this very issue!). I am closing this issue thusly.
