### ISSUE TITLE
Where do `learnyounode` store its data?

### ISSUE THREAD

**Issue by osenvosem** [workshopper/learnyounode#481]
I want to synchronise my completed tasks between computers. So, where the program stores the data about completed tasks?

**Comment by martinheidegger** [comment]
Depending on Operating system it stores it at different places. On Mac its in `~/.config/learnyounode/`

**Comment by osenvosem** [comment]
@martinheidegger sorry, it slipped my mind. It is MacOS. I managed to do what I wanted. Thank you.
