### ISSUE TITLE
os.tmpDir deprecated

### ISSUE THREAD

**Issue by cindygao93** [workshopper/learnyounode#492]
I get this error whenever I try to run learnyounode verify program.js:

(node:2951) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

Anyone have any idea how to fix it? I have the latest version of node, so I don't think it's that.

**Comment by SeanGallen** [comment]
I get the same warning after I updated node. It is something that has to be changed in Learnyounode and not on your end.  It is a friendly warning from Node that things are changing.

**Comment by martinheidegger** [comment]
This is a bug with wrapped-exec: https://github.com/workshopper/workshopper-wrappedexec/pull/10 Closing this issue in favor of the wrapped-exec issue.
