### ISSUE TITLE
HTTP File Server convention Q's

### ISSUE THREAD

**Issue by Chrinkus** [workshopper/learnyounode#499]
I was able to complete exercise 11 with the following code:
```javascript
var http = require("http"),
    fs = require("fs"),
    server, readable;

readable = fs.createReadStream(process.argv[3]);

server = http.createServer(function(req, res) {

    readable.pipe(res);
});

server.listen(process.argv[2]);
```
Though the above "passed" there was a red "x" and a note "Used fs method other than fs.createReadStream(): fs.createReadStream()". Is it recommended to create a new read stream object every request?

Also, the solution contained the line:
```javascript
res.writeHead(200, { 'content-type': "text/plain" });
```
What does this line actually accomplish?

**Comment by Mluka** [comment]
You should to search the Node.js API:

[response.writeHead](https://nodejs.org/api/http.html#http_response_writehead_statuscode_statusmessage_headers)

If you don't understand it. You should to learn some knowledge of HTTP.

**Comment by Chrinkus** [comment]
@Mluka yes, thank you. I attempted many node school workshoppers before my knowledge of what I was actually doing was ready. I'm good now!
