### ISSUE TITLE
[Suggestion]: Using the Native APIs with Juggling Async

### ISSUE THREAD

**Issue by 3DEsprit** [workshopper/learnyounode#504]
Hello all! 

When I was going through the Juggling Async problem, it didn't feel right to use a library to async the order. Not only because the functionality exists in the native environment, but that understanding of how to do this in a native environment is a crucial step to learning Node.js. Maybe it is just me, but it feels like this particular topic being taught to me from another source, is what really stood out to me when learning the V8 engine; understanding native async patterns, as well as the stream API in Node.js, especially when many do not even know it exists. 

Needless to say, would you not think this would be extremely important to learn as a new Node user (assuming that is the demographic for the majority of workshoppers)?

I know it may not really mean anything, and it may not be much, but here is the solution I created, which can be easily adapted to ES5 (since it is very little ES6):

```
var http = require('http');
var url = [];
url.push(process.argv[2]);
url.push(process.argv[3]);
url.push(process.argv[4]);

function getData(url, cb) { 
  var stream = [], out;
  http.get(url, (res) => {
    res.setEncoding('utf8');
    res.on('data', data => {
      stream.push(data);
    });
    res.on('end', (err, data) => {
      if(err) console.log(err);
      cb(console.log(stream.join('')));
    });
  });
}

getData(url[0], () => {
  getData(url[1], () => {
    getData(url[2], () => {
      // done
    });
  });
});
```

Of course this can be easily adapted for ES5, as the only ES6 really is the use of the fat arrows, but the concept is there. 

If it is too drastic I understand, but I had to at least bring it up.

**Comment by martinheidegger** [comment]
Thank you for pointing this out: There is the PR #426 that tries to tackle the same issue but hasn't been finished yet properly. If you want to improve on this it would awesome!

_(Closing this issue as a duplicate, please reopen if that was premature)_

**Comment by 3DEsprit** [comment]
Thanks again, and I will follow-up over at #426. 👍
