### ISSUE TITLE
Outputs same but the program judges the answer to be wrong.

### ISSUE THREAD

**Issue by SoberNod** [workshopper/learnyounode#506]
![screenshot from 2017-02-10 09-42-07](https://cloud.githubusercontent.com/assets/22790068/22813956/c05fd012-ef75-11e6-929c-0227559d9010.png)
Please explain.

Here is my code
`var net=require('net');
net.createServer(doFirst).listen(process.argv[2]);;

function doFirst(socket){
	var date=new Date();
 var year=date.getFullYear()  
   var month=  date.getMonth() +1;    // starts at 0  
  var dateO=   date.getDate()      // returns the day of month  
  var hours=   date.getHours()  
   var minutes=  date.getMinutes()  
if(month<10)
var x=year+'-0'+month+'-'+dateO+' '+hours+':'+minutes+'\n';
else
var x=year+'-'+month+'-'+dateO+' '+hours+':'+minutes+'\n';   
   socket.end(x);

}
`

**Comment by martinheidegger** [comment]
Hello @SoberNod 

Maybe you have found it by now but for all parts it is necessary to prefix with "0". in the error case you presented it tested `09` against `9`. Did you see the difference? Can I close this issue?

**Comment by martinheidegger** [comment]
Closing this issue. I hope that is okay.
