### ISSUE TITLE
[baby steps] sum output is correct but test not passing 

### ISSUE THREAD

**Issue by ionakathryn** [workshopper/learnyounode#524]
Hey so my code is as follows:

```
var count = 0;

for (var i = 0; i < process.argv[2].length; i++){
    count += Number(process.argv[2][i]);
}

console.log(count);
```

I'm really confused why this is not passing, im parsing to number and output is as expected. maybe its the way in which I'm accessing the array?

Thanks

**Comment by Duplicated** [comment]
You said the output is as expected? This is what I get when I run your code:

>                 ACTUAL                                 EXPECTED                
> ──────────────────────────────────────────────────────────────
   "6"                                 !=    "515"                              
   ""                                  ==    ""                                 
──────────────────────────────────────────────────────────────

Also, that is not how you access other arguments beyond the first one. What you wrote is basically accessing a 2D array name `process.argv`, which makes no sense since it's always a 1D array.

**Comment by ionakathryn** [comment]
OK thanks I will have to look into this when I am working on the IDE. What I mean by 'output is expected' is when I run the program, not the test, the output is as is expected e.g the 'correct answer'. So I'm struggling to see how it fails the test when I run it the correct answer appears.

Thanks

**Comment by Duplicated** [comment]
So you were saying that when you run `learnyounode run babystep.js` with the above code, you got the correct answer? 

Another thing I forgot to mention: `length` is a property of an Array object. When you dereference the Array object (such as `process.argv[2]`), what you get is no longer an Array object but instead the underlying element which could be anything (Number, String etc). Hence, `process.argv[2].length` is undefined, unless `process.argv[2]` is a nested Array object. What you want to do to get its length is `process.argv.length`, then take into account the first two arguments that aren't really numbers you care about (`process.argv[0]` is where you invoke the program `node` itself, while `process.argv[1]` is the path to your JS file).

**Comment by ProjectINT** [comment]
I have same problem, challenge verifying not working correct.
`const fs = require('fs');
const path = ('/Users/air');

fs.readdir(path, function (err, data) {
    if(err) {
        return console.log(err)
    }
    console.log(data);
});`
when i run `node program.js | leanyounode run program.js` it return correct array, but verifying not passed.

MY FIRST ASYNC I/O! challenge was passed after many times runs, each time verifying was return different value - how it's possible?

**Comment by ionakathryn** [comment]
Thank you for your response. After thinking about this, I found the solution and used .length in my for loop rather than hard coding the value of process.argv[2]. I am still getting used to JS syntax coming from a JAVA background but getting there!
