### ISSUE TITLE
http-collect solution cannot be verified

### ISSUE THREAD

**Issue by jonniedarko** [workshopper/learnyounode#54]
When running the solution provided [here](https://github.com/rvagg/learnyounode/tree/master/problems/http_collect) I get the following output 

```
Verifying "HTTP COLLECT"...

ACTUAL:   ""
EXPECTED: "123"

ACTUAL:   null
EXPECTED: "Flat out like a swag no worries as dry as a big smoke. 
Lets throw a fruit loop how as stands out like not my
bowl of rice. "

ACTUAL:   null
EXPECTED: ""

# FAIL

Your solution to HTTP COLLECT didn't match the expected output.
Try again!
```

**Comment by chiadt** [comment]
You try:

 var http = require('http')
    var bl = require('bl')
    
    http.get(process.argv[2], function (response) {
      response.pipe(bl(function (err, data) {
        if (err)
          return console.error(err)
        data = data.toString()
        console.log(data.length)
        console.log(data)
      }))  
    })
