### ISSUE TITLE
Make It Modular - Array with incorrect number of elements...

### ISSUE THREAD

**Issue by HandsomeMedia** [workshopper/learnyounode#541]
Strange error - As evidenced by results, it would seem I'm returning the right amount or Array elements - I tried multiple versions and still getting same error...  See code and results below:

mymodule.js:
```
const fs = require('fs'),
  path = require('path');

module.exports = (dirname, ext, callback) => {
  fs.readdir(dirname, (err, files) => {
    if (err) return callback(err);
    let arr = files.filter((name) => {
      return path.extname(name) === ('.' + process.argv[3]);
    });
    callback(null, arr);
  });
}

```
program.js:
```
const mymodule = require('./mymodule');
const print = (err, arr)=>{
  if(err) throw err;
  console.log(arr.join('\n'));
}
mymodule(process.argv[2], process.argv[3], print);

```

> Your submission results compared to the expected:
> 
>                  ACTUAL                                 EXPECTED
> ─────────────────────────────────────
>    "CHANGELOG.md"                      ==    "CHANGELOG.md"
>    "LICENCE.md"                        ==    "LICENCE.md"
>    "README.md"                         ==    "README.md"
>    ""                                  ==    ""
> ─────────────────────────────────────
> 
>  ✓ Submission results match expected
> 
>  ✓ Additional module file exports a single function
> 
>  ✓ Additional module file exports a function that takes 3 arguments
> 
>  ✓ Additional module file handles errors properly
> 
>  ✓ Additional module file handles callback argument
> 
>  ✓ Additional module file returned two arguments on the callback function
> 
>  ✓ Additional module file returned an Array as the second argument of the
>  callback
> 
>  ✓ Additional module file correctly handles '.'-prefixed extension
> 
>  ✗ Your additional module file [mymodule.js] did not return an Array with the
>  correct number of elements as the second argument of the callback

**Comment by AnshulMalik** [comment]
Hey, you should not use the process arguments inside `mymodule`, extension is passed to the exported function as parameter `ext`.

```
const fs = require('fs'),
  path = require('path');

module.exports = (dirname, ext, callback) => {
  fs.readdir(dirname, (err, files) => {
    if (err) return callback(err);
    let arr = files.filter((name) => {
      return path.extname(name) === ('.' + ext);
    });
    callback(null, arr);
  });
}
```

**Comment by HandsomeMedia** [comment]
@AnshulMalik - you nailed it, good catch.  I fixed that and the program ran correctly.  It seems like learnyounode gave the wrong error was given in my particular case.
Thanks!

**Comment by apatsekin** [comment]
Indeed error message is not very informative. Spent 20 minutes trying to figure out what's wrong with array size. The error was the same as yours.
