### ISSUE TITLE
Translation to Turkish language.

### ISSUE THREAD

**Issue by molcay** [workshopper/learnyounode#552]
I met by chance (not fully, freecodecamp) to this project, I used it but cannot see Turkish for language options of UI.

I want to translate this project to Turkish language for ones who not be comfortable in languages other than Turkish. 

I dug the project a bit, and I saw the UI made by other package _-not only this repo_ (such as [workshopper-adventure](https://github.com/workshopper/workshopper-adventure)). 

The questions are that:
1. Do I need to translate those repos, too?
and the
2. Can I get full list of repos which are need to be translated?

**Comment by AnshulMalik** [comment]
Hey @molcay, it's awesome to add another language support, it will be help to people.

Yes you are right, workshopper-adventure is what we use to handle the exercises.
But you just need to change files in this repo only.
- [Languages we support](https://github.com/workshopper/learnyounode/blob/master/learnyounode.js#L3)

Then add turkish exercise file to [exercises](https://github.com/workshopper/learnyounode/tree/master/exercises)

And we are good to go :)

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.

**Comment by molcay** [comment]
Hi, 
I finally finished the translation of the exercises to Turkish. 

Do I create a new **issue** or create **PR** directly?

**Comment by shanmukhateja** [comment]
Hi, please feel free to create a PR and add reference to this issue. I don't think a new issue is required in this case.

@feross any thoughts?

**Comment by feross** [comment]
Yep, a PR is fine!
