### ISSUE TITLE
Update solutions to use const and let

### ISSUE THREAD

**Issue by AnshulMalik** [workshopper/learnyounode#555]
We should move to const from var, let's start with solutions.
PRs are welcome 

- [x] baby_steps/solution/solutions.js
- [x] filtered_ls
- [x] hello_world
- [x] http_client
- [x] http_collect
- [x] http_file_server
- [x] http_json_api_server
- [x] http_uppercaserer
- [x] juggling_async
- [x] make_it_modular
- [x] my_first_async_io
- [x] my_first_io
- [x] time_server

To convert baby steps:
```diff --git a/exercises/baby_steps/solution/solution.js b/exercises/baby_steps/solution/solution.js
index 09835c4..d479a28 100644
--- a/exercises/baby_steps/solution/solution.js
+++ b/exercises/baby_steps/solution/solution.js
@@ -1,6 +1,6 @@
-var result = 0
+let result = 0

-for (var i = 2; i < process.argv.length; i++) {
+for (let i = 2; i < process.argv.length; i++) {
   result += Number(process.argv[i])
 }```

**Comment by martiuslim** [comment]
Hi, I'll be submitting a pr regarding this soon but I think hello_world does not need any changes since every solution there is simply a `console.log()`

**Comment by AnshulMalik** [comment]
Thanks @martiuslim
