### ISSUE TITLE
Update exercises to use const and let instead of var

### ISSUE THREAD

**Issue by AnshulMalik** [workshopper/learnyounode#559]
We are gradually migrating from `var` to `const`. The exercises still contains code that uses `var` we should change `var` usage to `const` or `let` as applicable.

PRs welcome :)
Please create one PR per exercise and a change should be applied to the translations as well. 

- [x] baby_steps/solution/solutions.js
- [x] filtered_ls
- [x] hello_world
- [x] http_client
- [x] http_collect
- [x] http_file_server
- [x] http_json_api_server
- [ ] http_uppercaserer
- [x] juggling_async
- [x] make_it_modular
- [x] my_first_async_io
- [x] my_first_io
- [x] time_server

**NOTE:**
- **Please consider the `problem.md` and it's translation files as well**
- **Add "use strict" to top of file to pass the tests :)**
- Create PR against `es6` branch

**Comment by iampeterbanjo** [comment]
I would like to help out with this task for hacktoberfest

**Comment by AnshulMalik** [comment]
Go ahead @iampererbanjo :)

**Comment by shangyilim** [comment]
i would like to help out as well. Would that be cool?

**Comment by AnshulMalik** [comment]
Yes @shangyilim , that would be great!

**Comment by shangyilim** [comment]
@AnshulMalik  since we are updating it for ES6, can i also suggest updating the module imports from `require` to `import `?

**Comment by AnshulMalik** [comment]
@shangyilim That's a great idea and we will definitely look forward to incorporate es6 imports as well

But it's not a straight forward solution since node directly doesn't support imports yet, so we need to use babel. Currently, our testing infrastructure doesn't support babel.
So first we need to adopt babel in [workshopper-adventure](https://github.com/workshopper/workshopper-adventure) then only we can update the exercises here.
It'd be awesome if you can help us there as well :)

**Comment by martiuslim** [comment]
@iampeterbanjo @shangyilim hi guys, I've already started on this a few days back. We can work on it together but just take note that baby_steps #563 and filtered_ls #564 has been done :smile:

**Comment by shangyilim** [comment]
i have sent a PR under #565

**Comment by AnshulMalik** [comment]
@shangyilim @martiuslim Please consider the `problem.md` and translation files as well.
And if possible, please keep one PR per exercise, it'd be easier to review..

**Comment by shangyilim** [comment]
@AnshulMalik  noted, the `problem.md` and translations examples will be updated if they contain `var` as well.

**Comment by martiuslim** [comment]
@AnshulMalik noted.

**Comment by n0f3** [comment]
would love to help out, anybody started on http client?

**Comment by iampeterbanjo** [comment]
I haven't

**Comment by agomez314** [comment]
Hello, what is the status of this change?

**Comment by anshulmalik1** [comment]
@agomez314 Hey, we are still left with some files that needs to be changed

**Comment by AnshulMalik** [comment]
@agomez314, Yes, we are still behind, some files needs the change.

**Comment by isaacchien** [comment]
i'll work on http_client

**Comment by isaacchien** [comment]
Never mind looks like somebody has already updated http_client to es6, but it hasn't been marked as completed yet on this issue.

**Comment by AnshulMalik** [comment]
Great! We are 84% done now :)

**Comment by martiuslim** [comment]
remaining 2, please fix your PRs guys :smile: 

@iampeterbanjo #571 
@shangyilim #580

**Comment by Tanis-02** [comment]
Hi, I was wondering if you still wanted help with this? This is one of my first contributions to open source projects so forgive me if this is a stupid question but, by translation do you mean the language which the code is written? If so I know English and Spanish so I could help out in either of those 2 categories. Not sure if it's any help!

**Comment by feross** [comment]
I finished converting everything from `var` to `const` and merged to `master` but I didn't realize there was an `es6` branch already. So I duplicated some of the work, but I used the excellent `lebab` tool so it didn't take me very long.

**Comment by feross** [comment]
Since there were other non-`let` and `const` changes to convert to ES6, like the use of template strings, et.c on the `es6` branch, I just merged it into `master` as well, so all these improvements are now on `master` :)

🎉
