### ISSUE TITLE
Windows 10, Node.js command prompt, learnyounode not installing

### ISSUE THREAD

**Issue by justice47** [workshopper/learnyounode#561]
Hello.
Im installing learnyounode in a proper way via npm.
It fails with errors:
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "learnyounode"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\System32\npm-debug.log

[npm-debug.txt](https://github.com/workshopper/learnyounode/files/1301362/npm-debug.txt)

**Comment by AnshulMalik** [comment]
As the logs says, it might want to use git for something. Do you have `git` installed?

**Comment by justice47** [comment]
Yes, I have installed it from https://git-for-windows.github.io/

**Comment by ankurnecessary** [comment]
I have also faced the same issue.
