### ISSUE TITLE
Cannot install learnyounode

### ISSUE THREAD

**Issue by speletero** [workshopper/learnyounode#562]
here npm-debug.log file

Thanks 

[npm-debug.txt](https://github.com/workshopper/learnyounode/files/1316411/npm-debug.txt)

**Comment by Flet** [comment]
I see this near the end of the debug:
>41592 verbose stack Error: not found: git

This means one of the things learnyounode depends on needs to use the `git` command (probably to download another package?)

Try installing git from here: https://git-scm.com/download/

Note that you may need to re-open your cmd window after git is installed to pick up changes to the Windows Path.

**Comment by speletero** [comment]
thanks flet !!

the problem and the solution was this: https://stackoverflow.com/questions/26620312/installing-git-in-path-with-github-client-for-windows
