### ISSUE TITLE
Warning: deprecated safe-to-string-x

### ISSUE THREAD

**Issue by sevku** [workshopper/learnyounode#583]
I've just installed learnyounode and it gave me the following Warning:

deprecated safe-to-string@2.0.3: Moved to https://github.com/Xotic750/to-string-symbols-supported-x

**Comment by shanmukhateja** [comment]
This needs to be inspected and fixed immediately. Usage of deprecated deps is never encouraged.

**Comment by Flet** [comment]
This is no longer a dependency, closing.
