### ISSUE TITLE
install locally

### ISSUE THREAD

**Issue by octodevelopers** [workshopper/learnyounode#584]
Hi,

I would like to install the learnyournode from the local cloned repository (the zip file downloaded)
and not from the npm command online.

What is the best way for doing so? are there any special dependencies or requierments?
Thanks!

**Comment by shashank036** [comment]
I need the same answer. if anyone who can help please share your feedback on how to install this.
Via npm i am getting this msg

`npm ERR! path C:\Users\Codex\AppData\Roaming\npm\node_modules\learnyounode
npm ERR! code EISGIT
npm ERR! git C:\Users\Codex\AppData\Roaming\npm\node_modules\learnyounode: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\Codex\AppData\Roaming\npm\node_modules\learnyounode
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Codex\AppData\Roaming\npm-cache\_logs\2018-01-12T22_58_15_286Z-debug.log`

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
