### ISSUE TITLE
Error When Install

### ISSUE THREAD

**Issue by TurkiBt** [workshopper/learnyounode#587]
C:\node>npm install -g learnyounode
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Turki\AppData\Roaming\npm-cache\_logs\2017-11-04T20_27_50_
088Z-debug.log

I don't understand :(

**Comment by AnshulMalik** [comment]
Do you have git installed? [https://git-scm.com/download/win](https://git-scm.com/download/win)

**Comment by sherib29** [comment]
I had the same issue on my Windows 10 machine.  I installed git locally, opened git cmd and ran 
npm install -g learnyounode 
from there without issue.
