### ISSUE TITLE
Documentation URLs lead nowhere...

### ISSUE THREAD

**Issue by sometowngeek** [workshopper/learnyounode#588]
With your problem.md, I'm noticing issues with finding documentation because the suggested URLs don't point to accessible documentation. It seems to point to a local source instead.

Can you please fix the URLs so they point to accessible sources like web pages?

Thank you :)

-STG

See some examples here:
<img width="1506" alt="screen shot 2017-11-07 at 10 54 40 am" src="https://user-images.githubusercontent.com/11671755/32506460-452a3996-c3aa-11e7-8544-8f426e45533b.png">
<img width="1506" alt="screen shot 2017-11-07 at 10 57 51 am" src="https://user-images.githubusercontent.com/11671755/32506613-a6dab2b0-c3aa-11e7-89e5-cdb960266370.png">
<img width="1506" alt="screen shot 2017-11-07 at 10 58 13 am" src="https://user-images.githubusercontent.com/11671755/32506611-a6a331aa-c3aa-11e7-8b1c-427ce03959ef.png">
<img width="1506" alt="screen shot 2017-11-07 at 10 58 23 am" src="https://user-images.githubusercontent.com/11671755/32506612-a6c6bdbe-c3aa-11e7-8f67-bfba11880fd8.png">

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
