### ISSUE TITLE
filterted_ls not working properly

### ISSUE THREAD

**Issue by hamzahamidi** [workshopper/learnyounode#591]
Here's my code:
```
fs = require('fs');

fs.readdir(process.argv[2], (err, list) => {
    if (err) console.log('error:', err);
    else {
        console.log(list.filter(item => item.endsWith('.' + process.argv[3])));
    }
})
```

When I try to verify the program I get this logs:
# LEARN YOU THE NODE.JS FOR MUCH WIN!

## FILTERED LS (Exercise 5 of 13)

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "[ 'CHANGELOG.md', 'LICENCE.md', 'README.md' ]" !=    "CHANGELOG.md"                     
   ""                                  !=    "LICENCE.md"                       
                                       !=    ""                                 

────────────────────────────────────────────────────────────────────────────────

 ✗ 

 Submission results did not match expected!

 ✓ 

 Used asynchronous method: fs.readdir()

 # FAIL Your solution to FILTERED LS didn't pass. Try again!

─────────────────────────────────────────────────────────────────────────────

  » To print these instructions again, run: learnyounode print                
  » To execute your program in a test environment, run: learnyounode run                                                                          
    program.js                                                                
  » To verify your program, run: learnyounode verify program.js               
  » For help run: learnyounode help

**Comment by harrisi** [comment]
[`Array.prototype.filter()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) returns an array, whereas this challenge expects several string output to the console.
