### ISSUE TITLE
url api has changed

### ISSUE THREAD

**Issue by sethchilders92** [workshopper/learnyounode#593]
Exercise 13
In the solution, you used 
```
var time = new Date(parsedUrl.query.iso)
```
and after looking into it, url.query is no longer used.
The new way to do it is using url.searchParams. You might want to update your solution.
You can read more about it here: https://nodejs.org/api/url.html#url_class_urlsearchparams

Thanks!

**Comment by AnshulMalik** [comment]
It was added in node v7.5.0, and we support node v > 4.8 so doing this would break for earlier versions.
What do you say @martinheidegger ?

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.

**Comment by feross** [comment]
I updated all exercises to use WHATWG `URL` instead of `require('url')` so this can be closed.
