### ISSUE TITLE
ERR! missing script: learnyounode

### ISSUE THREAD

**Issue by philawesomer** [workshopper/learnyounode#595]
I have no idea what to do beyond this point. Some help would be greatly appreciated.

C:\Users\user>npm run learnyounode
npm ERR! missing script: learnyounode

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-12-12T11_49_30_136Z-debug.log

**Comment by AnshulMalik** [comment]
You should installl it using `npm install -g learnyounode`
And then simple run by `learnyounode`

**Comment by philawesomer** [comment]
I thought I had done that already, but here it is again: 

C:\Users\user>npm install -g learnyounode
C:\Users\user\AppData\Roaming\npm\learnyounode -> C:\Users\user\AppData\Roaming\npm\node_modules\learnyounode\bin\learnyounode
+ learnyounode@3.5.10
updated 1 package in 19.952s

C:\Users\user>npm run learnyounode
npm ERR! missing script: learnyounode

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2017-12-12T12_27_31_240Z-debug.log

**Comment by AnshulMalik** [comment]
Instead of `npm run learnyounode`, you should only do `learnyounode`
