### ISSUE TITLE
Make It Modular - The correct answer doesn't pass.

### ISSUE THREAD

**Issue by IlyaLoshchinin** [workshopper/learnyounode#597]
A problem with third test.
> Your additional module file [filterModule.js] does not appear to pass back
 an error received from fs.readdir(). Use the following idiomatic Node.js
 pattern inside your callback to fs.readdir(): if (err) return
 callback(err)

My solution
 **main.js:**
```javascript
const filter = require('./filterModule');
const [, , pathFolder, extension] = process.argv;
 filter(pathFolder, extension, (err,data)=>{
    if(err){
        console.error(err);
        return;
    }
    data.forEach(el => console.log(el));
 });
```

 **filterModule.js:**
```javascript
const fs = require('fs');

module.exports = function(directoryPath, extension, callback) {
  if (!directoryPath || !extension) {
    return callback(new Error('No arguments!'));
  }

  //PASS
  // fs.readdir(directoryPath, 'utf-8', (err, files) => {
  //   if (err) return callback(err);
  //   callback(null, files.filter(el => el.endsWith(`.${extension}`)));
  // });

  //NOT PASS
  fs.stat(directoryPath, (err, stats) => {
    if (err) return callback(err);
    if (stats.isDirectory()) {
      fs.readdir(directoryPath, 'utf-8', (err, files) => {
        if (err) return callback(err);
        callback(null, files.filter(el => el.endsWith(`.${extension}`)));
      });
    }
  });
};
```
In my opinion this is quite the correct answer.

**Comment by AnshulMalik** [comment]
Yes @IlyaLoshchinin the solution is correct. It's the way we test the solution for correctness which is not valid for this test case, we expect `fs.readdir` to be directly called in the program, and in this case, it's called inside of callback from `fs.stat`

Great catch!

Would you like to fix this ?

https://github.com/workshopper/learnyounode/blob/master/exercises/my_first_io/wrap.js#L20
Looks like we only check for first item in callstack, which might not be our program(this example) so we need to go up few items and check if it matches the calling program.

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
