### ISSUE TITLE
Unable to complete HTTP File Server

### ISSUE THREAD

**Issue by scottksmith95** [workshopper/learnyounode#6]
I wrote out my code for the exercise and it was failing with the following error:

```
var fs = require('fs');
var http = require('http');

var path = process.argv[2];

var server = http.createServer(function (request, response){
    var src = fs.createReadStream(path);
    src.pipe(response);
});

server.listen(8000);
```

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Parse Error
    at Socket.socketOnData (http.js:1584:20)
    at TCP.onread (net.js:525:27)

I then tried the solution code in the repository (see below) and it too is failing with the same error.

```
var http = require('http');
var fs = require('fs');

var server = http.createServer(function (req, res) {
  fs.createReadStream(process.argv[2]).pipe(res);
  res.end();
});
server.listen(8000);
```

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Parse Error
    at Socket.socketOnData (http.js:1584:20)
    at TCP.onread (net.js:525:27)

I am running the latest version of node v0.10.16

**Comment by Silerra** [comment]
process.argv[2] gives a port number. But createReadStream need a path to file. This path find you in process.argv[3]. ;-)
