### ISSUE TITLE
TimeOutOverflowWarning when HTTP File Server

### ISSUE THREAD

**Issue by NJM8** [workshopper/learnyounode#602]
Hello, 

I am getting this error when I run or verify my HTTP File Server:
(node:15810) TimeoutOverflowWarning: 4294967296000 does not fit into a 32-bit signed integer.
Timer duration was truncated to 2147483647.

I get the same error when running the official solution. Is this something to be fixed for just a byproduct of a simple lesson?

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
