### ISSUE TITLE
Commands aren't displayed

### ISSUE THREAD

**Issue by EvgeniyZ** [workshopper/learnyounode#607]
Hi, I've been installed learnyounode version: '3.5.10' and noticed that most of commands aren't displayed in CLI (Powershell).
Windows 10, Node 8.6.0.
Below is a cli output from learnyounode my first async i\o challenge.

 # LEARN YOU THE NODE.JS FOR MUCH WIN!

 ## MY FIRST ASYNC I/O! (Exercise 4 of 13)

  Write a program that uses a single asynchronous filesystem operation to
  read a file and print the number of newlines it contains to the console
  (stdout), similar to running .

  The full path to the file to read will be provided as the first
  command-line argument.

 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

 # HINTS

  The solution to this problem is almost the same as the previous problem
  except you must now do it the Node.js way: asynchronous.

  Instead of  you will want to use  and instead of using the return value of
  this method you need to collect the value from a callback function that
  you pass in as the second argument. To learn more about callbacks, check
  out: (https://)

  Remember that idiomatic Node.js callbacks normally have the signature:

     function callback (err, data) { /* ... */ }

  so you can check if an error occurred by checking whether the first
  argument is truthy. If there is no error, you should have your  object as
  the second argument. As with , you can supply 'utf8' as the second
  argument and put the callback as the third argument and you will get a
  instead of a .

  Documentation on the  module can be found by pointing your browser here:
  file://C:\Users\**\AppData\Roaming\npm\node_modules\learnyou
  node\node_apidoc\fs.html

 ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

   » To print these instructions again, run:
   » To execute your program in a test environment, run:
   » To verify your program, run:
   » For help run:

**Comment by ansromanov** [comment]
Can confirm this bug with Ubuntu 17.10 and Node v8.9.4.
Here is my output:

 # LEARN YOU THE NODE.JS FOR MUCH WIN!  
   
 ## MY FIRST I/O! (Exercise 3 of 13)  
   
  Write a program that uses a single synchronous filesystem operation to  
  read a file and print the number of newlines (\n) it contains to the  
  console (stdout), similar to running .  
   
  The full path to the file to read will be provided as the first  
  command-line argument (i.e., process.argv[2]). You do not need to make  
  your own test file.

**Comment by kmswic** [comment]
I  have the same issue on learnyounode@3.5.10 with OSX 10.11.6, Node 8.0.0
Sample output:


## HINTS

  The  method takes a pathname as its first argument and a callback as its
  second. The callback signature is:

     function callback (err, list) { /* ... */ }

  where  is an array of filename strings.

  Documentation on the  module can be found by pointing your browser here:
  file:///Users/konrad/.config/yarn/global/node_modules/learnyounode/node_ap
  idoc/fs.html

  You may also find node's  module helpful, particularly the  method.

  Documentation on the  module can be found by pointing your browser here:
  file:///Users/konrad/.config/yarn/global/node_modules/learnyounode/node_ap
  idoc/path.html

 ─────────────────────────────────────────────────────────────────────────────

   » To print these instructions again, run:
   » To execute your program in a test environment, run:
   » To verify your program, run:
   » For help run:

**Comment by spaceexperiment** [comment]
Same issue on Ubuntu 17.10.

**Comment by martinheidegger** [comment]
This should have been fixed with the publication of a depending library. Can you verify that it works now?

**Comment by spaceexperiment** [comment]
yep, it's seems to be working now.
