### ISSUE TITLE
Juggling Async: Possible Solution with native Promises?

### ISSUE THREAD

**Issue by mtrivera** [workshopper/learnyounode#611]
Is it possible to solve this with Promises? I'm running into errors and would like to know if its even possible to use promises or its coded NOT to work with promises.

**Comment by AnshulMalik** [comment]
Not sure why it's not accepting the solution with promise. Can you share the code?

**Comment by mtrivera** [comment]
```javascript
const http = require('http');
const bl = require('bl');
const urls = [process.argv[2], process.argv[3], process.argv[4]];

Promise.all(urls).then((urls) => {
  return urls.map((u) => {
    jugAsync(u);
  });
});

function jugAsync(url) {
  http.get(url, (res) => {
    res.pipe(bl(function(error, data) {
      const str = data.toString();
      console.log(data + '\n');
    }))
  }).on('error', function(e) {
    console.error(error);
  });
}
```

**Comment by AnshulMalik** [comment]
> The catch is that you must print them out in the same order as the URLs are provided to you as command-line arguments

So using promises in this manner won't guarantee that `console.log`s will be in order. Hope you get it
