### ISSUE TITLE
The word "completed" for each challenge is cut off when it verified a second time.

### ISSUE THREAD

**Issue by LeidyGil** [workshopper/learnyounode#615]
When the challenge is verified for second time, the text cut off.

See the following image:

![image](https://user-images.githubusercontent.com/26014869/37559267-16d0eeac-29f1-11e8-90dc-739cc796f40a.png)

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
