### ISSUE TITLE
MY FIRST I/O / fs.readFileSync FAIL

### ISSUE THREAD

**Issue by todd-dsm** [workshopper/learnyounode#616]
First time caller - big believer. Found an discrepancy; should be an easy fix:

Instructions are clear about using the `readFileSync()` method. On verification though, the program fails for using it:
```bash
learnyounode verify yo.js
...
## MY FIRST I/O! (Exercise 3 of 13)

Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   ""                                  !=    "27"                               

────────────────────────────────────────────────────────────────────────────────
```

`readFileSync()` produces no output. 

When using the `readFile()` method the correct number of lines is output but the program fails for using it.
```bash
$ learnyounode verify yo.js 
...
## MY FIRST I/O! (Exercise 3 of 13)


Your submission results compared to the expected:

                 ACTUAL                                 EXPECTED                
────────────────────────────────────────────────────────────────────────────────

   "3"                                 ==    "3"                                
   ""                                  ==    ""                                 

────────────────────────────────────────────────────────────────────────────────

 ✓ 

 Submission results match expected

 ✗ 

 Used asynchronous method: fs.readFile()

 # FAIL Your solution to MY FIRST I/O! didn't pass. Try again!
```

Even the solution doesn't use `readFileSync()` ;-)

Thank you for sharing your knowledge.

**Comment by kcpn** [comment]
Mine is working correctly.

at the last part though, doesn't that mean that because you used fs.readFile(),
that's why it's showing `x` ?

```
✓ 

 Submission results match expected

 ✗ 

 Used asynchronous method: fs.readFile()

 # FAIL Your solution to MY FIRST I/O! didn't pass. Try again!
```

maybe there's something with your code?

**Comment by higornevesmarques** [comment]
> First time caller - big believer. Found an discrepancy; should be an easy fix:
> 
> Instructions are clear about using the `readFileSync()` method. On verification though, the program fails for using it:
> 
> ```shell
> learnyounode verify yo.js
> ...
> ## MY FIRST I/O! (Exercise 3 of 13)
> 
> Your submission results compared to the expected:
> 
>                  ACTUAL                                 EXPECTED                
> ────────────────────────────────────────────────────────────────────────────────
> 
>    ""                                  !=    "27"                               
> 
> ────────────────────────────────────────────────────────────────────────────────
> ```
> 
> `readFileSync()` produces no output.
> 
> When using the `readFile()` method the correct number of lines is output but the program fails for using it.
> 
> ```shell
> $ learnyounode verify yo.js 
> ...
> ## MY FIRST I/O! (Exercise 3 of 13)
> 
> 
> Your submission results compared to the expected:
> 
>                  ACTUAL                                 EXPECTED                
> ────────────────────────────────────────────────────────────────────────────────
> 
>    "3"                                 ==    "3"                                
>    ""                                  ==    ""                                 
> 
> ────────────────────────────────────────────────────────────────────────────────
> 
>  ✓ 
> 
>  Submission results match expected
> 
>  ✗ 
> 
>  Used asynchronous method: fs.readFile()
> 
>  # FAIL Your solution to MY FIRST I/O! didn't pass. Try again!
> ```
> 
> Even the solution doesn't use `readFileSync()` ;-)
> 
> Thank you for sharing your knowledge.

Make sure that you are using ```\n``` instead of ```/n```, it is a common mistake :)

**Comment by shanmukhateja** [comment]
This issue can be closed for inactivity. Also, it seems there has been a solution provided however it hasn't been confirmed.
If anybody else has the same issue, it can be re-opened.
