### ISSUE TITLE
Using learnyounode content as a basis for a Getting Started section in the Node.js Website

### ISSUE THREAD

**Issue by bnb** [workshopper/learnyounode#617]
Hello! 👋

I wanted to reach out to y'all and say that the Node.js Website Redesign Initiative is working on a Getting Started section to include in a full redesign of the Node.js website, and we'd really love to base the contents of it off of the content in `learnyounode`.

Obviously this will be a website and not an interactive CLI, so we'll likely modify the content to some degree, but we wanted to reach out with an offer to join in on the meeting where we'll be discussing this.

Here's the link to the [issue for that meeting](https://github.com/nodejs/website-redesign/issues/27) - time and date are still TBD!

Would be really stellar to get feedback from y'all on this - if it's a good idea, if you have any suggestions on how we could improve, or if y'all have any specific concerns about this.

Thanks! ❤️

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.

**Comment by feross** [comment]
@bnb Lmk if this is still something you'd like feedback on. I'm attempting to clean up this issue tracker a bit and so am closing stale issues.
