### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by lawsonjt** [workshopper/learnyounode#638]
I'm on the first exercise and created program.js with console.log('HELLO WORLD') inside it.
In the terminal after running **learnyounode**  I type **learnyounode run program.js**

> Could not run: TypeError: Cannot read property 'toString' of undefined
>     at Exercise.setup (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/workshopper-exercise/filecheck.js:8:22)
>     at next (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:145:15)
>     at Exercise.setup (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:151:5)
>     at Exercise.runVerify (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:158:8)
>     at Exercise.run (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/workshopper-exercise/exercise.js:168:13)
>     at WA.executeExercise (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:429:16)
>     at WA.process (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:321:17)
>     at WA.run (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/workshopper-adventure/index.js:265:15)
>     at Object.exports.handler (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/workshopper-adventure/lib/commands/run.js:12:21)
>     at method.valid.$ (/Users/joshua/.npm-packages/lib/node_modules/learnyounode/node_modules/commandico/commandico.js:143:15)

**Comment by ccarruitero** [comment]
Hi @lawsonjt 

Could you solve the problem?
If not, can you give us details about node version and os you are using?

**Comment by shanmukhateja** [comment]
This issue can be closed due to inactivity. Please feel free to re-open the issue if you have something to contribute to it.
