### ISSUE TITLE
JSON API server offset missing in Unix time?

### ISSUE THREAD

**Issue by kushalmahajan** [workshopper/learnyounode#645]
Don't you think guys, offset is an issue while returning `d.getTime()`;

I think it should be 

```
function getUnixTime(d) {
    const offset = d.getTimezoneOffset() * 60 * 1000;
    const withOffset = d.getTime();
    return withOffset - offset;
}
```

I just referred here - https://stackoverflow.com/questions/9229213/convert-iso-date-to-milliseconds-in-javascript

Let me know your thoughts for timeZone difference!

**Comment by ccarruitero** [comment]
Hi @kushalmahajan,

I don't think offset will be a problem in this case since you are running and using the server in local.

**Comment by shanmukhateja** [comment]
This issue can be closed as it does not seem to be a real bug.
