### ISSUE TITLE
Package not found by NPM

### ISSUE THREAD

**Issue by ElliotFriedman** [workshopper/learnyounode#652]
When trying to install via nom, I am getting a not found error:

"http fetch GET 404 https://registry.npmjs.org/learnyournode 173ms
 silly fetchPackageMetaData error for learnyournode@latest 404 Not Found: learnyournode@latest"

I visited https://registry.npmjs.org/learnyournode and sure enough, I got a {"error":"Not found"}, please help

**Comment by aadilayub** [comment]
I'm having trouble installing via npm as well, running Fedora 29

[
![screenshot from 2019-01-05 18-18-07](https://user-images.githubusercontent.com/31581044/50724884-5c7a9180-1116-11e9-8822-2cf0540c1ea2.png)
](url)

**Comment by ccarruitero** [comment]
I think we should close this, since seems resolved.

cc @AnshulMalik
