### ISSUE TITLE
Change the module name `map` under exercise HTTP UPPERCASERER

### ISSUE THREAD

**Issue by shivangg** [workshopper/learnyounode#655]
The `through2-map` module is stored with the variable name `map` which introduces confusion as there is already a standard `map` method in the Array prototype.  

![image](https://user-images.githubusercontent.com/10586637/51684158-7e7a7c00-2011-11e9-8aa5-73dd215a8a22.png)

**Comment by ccarruitero** [comment]
Hi @shivangg 

I don't think this change is necessary.

We just declare a variable named map, and the file is not too big for loose the reference where is declared.

Aside, you can name the variable how you prefer when do the exercise. This is just a solution for reference.

**Comment by shanmukhateja** [comment]
This issue can be closed as it does not seem to be a real bug.
