### ISSUE TITLE
Update problems to use const and let

### ISSUE THREAD

**Issue by shisama** [workshopper/learnyounode#660]
Hi, I like learnyounode. This workshop helped me to learn Node.js.
However, this workshop is a little outdated.
This is the proposal to replace var to let/const in problem.md like solution (PR: https://github.com/workshopper/learnyounode/issues/555).
The below list indicates problem.md including 'var'.

- [ ] http_collect
- [ ] http_file_server
- [ ] http_uppercaserer
- [ ] make_it_modular
- [ ] my_first_io
- [ ] time_server

**Comment by shanmukhateja** [comment]
It seems this issue can be closed as the referred PR  seems to have achieved the propositions made.
