### ISSUE TITLE
remove node_apidocs

### ISSUE THREAD

**Issue by ccarruitero** [workshopper/learnyounode#669]
We have a copy of node api docs, but I think is double work since node maintain your docs very well. Aside the folder is not updated some time ago.

So, I propose to remove that and link to official node api in exercises where needed.

What do you think?

**Comment by AnshulMalik** [comment]
I am not sure why are we having the docs folder either. @martinheidegger do you know?

**Comment by feross** [comment]
I believe this was initially added so that the workshop would work offline at NodeConf US which took place at Walker Creek Ranch, where internet was sparse. I'd rather just delete this and point to the live docs for now, since those are at least not out of date.

**Comment by AnshulMalik** [comment]
Okay, let's go with that then.

**Comment by feross** [comment]
PR to remove the outdated offline docs here: https://github.com/workshopper/learnyounode/pull/678
