### ISSUE TITLE
HTTP File Server run/verify failed

### ISSUE THREAD

**Issue by lijian** [workshopper/learnyounode#68]
Thrown error:

Error connecting to http://localhost:14593: connect ECONNREFUSED

but when I run by node directly, it works correctly.

While when I try to run it again and again, sometime it will pass..., i think it may a bug?

**Comment by theJ8910** [comment]
I also have encountered this problem on the time server exercise. I'm running learnyounode with io.js on an older machine; typically launching node takes it around 1 second or so to start up. I can confirm that lijian's solution of changing the timeout to 5 seconds is a workaround to the problem.

**Comment by brentonklassen** [comment]
I have nearly the same issue, only I know that my code is wrong, yet my solution passes -- with errors! 
![image](https://cloud.githubusercontent.com/assets/5440188/6405995/2fdac140-bdf0-11e4-8c80-b2d3e076096c.png)

My code is:

var net = require('net');
var date = new Date();
var formattedDate = date.getFullYear()+'-'+date.getMonth()+'-'+date.getDate()+' '+date.getHours()+':'+date.getMinutes();

var server = net.createServer(function(socket){
        socket.end(formattedDate);
}).listen(Number(process.argv[2]));

I am using VirtualBox through Vagrant.

**Comment by dylanwind** [comment]
I also struggled for a while on this issue, and unfortunately the workaround "enlarge timeout" does not work for me.

But anyway, I finally find it can be tested by client - server communication.

This is server code
```javascript 
var fs = require('fs')
var http = require('http')

var filename = process.argv[2]

var server = http.createServer(function(req, res) {
	fs.createReadStream(filename).pipe(res)
});

server.listen(8000)
```

start server by 
```javascript
node file_server.js "D:\GitRepos\new.txt"
```

Open another terminal, and start a client by
```javascript
curl localhost:8000
```

Then you will find new.txt content output on client side.

**Comment by lalitb** [comment]
I am facing same timeout issue with learnyounode, while it works fine when running directly under node. Which timeout I need to increase as  workaround?
Here is my code for http server:
--clip--
var http=require('http');
var fs=require('fs');

var filename = process.argv[2];

var server = http.createServer(function ( req, res) {
        res.socket.setTimeout(10000);
        var freadStream = fs.createReadStream(filename);

        freadStream.pipe(res);
});
server.listen(8000);
--clap--

**Comment by Shadocko** [comment]
Hello,
I'm experiencing a similar but slightly different issue on a Beaglebone Black: learnyounode verify will just hang after printing the two error lines:
    Error connecting to http://localhost:XYZ: connect ECONNREFUSED
Problem solved after editing /usr/local/lib/node_modules/learnyounode/exercises/http_file_server/exercise.js and replacing 500 with 1500 in the setTimeout call.
node v0.10.38
learnyounode v2.7.1

**Comment by insanux** [comment]
Try you to set port numer of listen() taking it from a command argument.

**Comment by th-santos** [comment]
https://github.com/workshopper/learnyounode/issues/68#issuecomment-128153041

Works fine! I have to change to 2500.

**Comment by DravitLochan** [comment]
Finally it worked for me. Seems learnyounode has to be installed globally. Uninstall current version and simply run 
```
sudo npm uninstall learnyoucode
sudo npm install learnyounode -g
```
Worked for me at-least!

**Comment by shanmukhateja** [comment]
This issue can be marked as closed as it seems to have been resolved. Feel free to reopen the issue if you have something to contribute to it.

**Comment by zerotobtc** [comment]
> I also had this problem with ”uppercase” exercise only, and workaround was the same (increase timeout value from 500 to 1000). I’m running node (0.10.30, learnyounode@1.0.1) in powerful Windows 7 machine.
> 
> %APPDATA%\npm\node_modules\learnyounode\exercises\http_uppercaserer\exercise.js
> ` setTimeout(query.bind(this, mode), 1000) // was 500 `

I'm on linux and simply did the same thing. Worked perfectly fine, thanks for the hint!
