### ISSUE TITLE
using the function directly off fs rather than using fs itself

### ISSUE THREAD

**Issue by timoxley** [workshopper/learnyounode#69]
Apparently `make it modular` won't verify if you use: 

``` js
var readdir = require('fs').readdir;
readdir(dirname, function(err, list){ ... }
```

instead of:

``` js
var fs = require('fs');
fs.readdir(dirname, function(err, list){ ... }
```

https://github.com/nodeschool/discussions/issues/141

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
