### ISSUE TITLE
Exercise 4 Correct Answer, still fail?

### ISSUE THREAD

**Issue by kingram6865** [workshopper/learnyounode#705]
![Exercise4-Error](https://user-images.githubusercontent.com/13263318/80191069-0f038b80-85ca-11ea-8ed6-ba5a2a2defa5.png)

The Code:
```
const fs = require('fs');
const file = process.argv[2];
const str = fs.readFileSync(file).toString();
const result = str.split('\n');
console.log(result.length-1);
```
Why the FAIL?

**Comment by jordanSu** [comment]
The second testing result shows that you used synchronous method, however in Exercise 4 an asynchronous method should be used.

**Comment by ccarruitero** [comment]
Closing since question was answered. Thanks @jordanSu
