### ISSUE TITLE
module installation

### ISSUE THREAD

**Issue by myearnings1054** [workshopper/learnyounode#718]
Hello,
failed to install the learning module for Nodeschool.  Can you, please, tell me what needs to be done?
Thank you.

![screenshot_install 0 2](https://user-images.githubusercontent.com/77245293/121082209-d5eaa280-c7ee-11eb-9460-dc47a2b86d94.png)

**Comment by dimitri-bourreau** [comment]
_(should this issue be closed?)_

**Comment by martinheidegger** [comment]
Indeed, thanks @dimitri-bourreau

**Comment by myearnings1054** [comment]
Hello, 
thank you for your reply.
Unfortunately, after entering the command for javascript, there was nothing in the folder Roaming. Can you, please, tell me if this can be fixed?
Thank you.
