### ISSUE TITLE
The baby steps official solution

### ISSUE THREAD

**Issue by vitkarpov** [workshopper/learnyounode#8]
We could use `Array.prototype.forEach` instead plain `for (var i = 2; i < process.argv.length; i++) { ... }`, couldn't we?

So the solution might be

``` javascript
var total = 0;

process.argv.forEach(function(item) {
  //we need to exclude first and second items
  //so we could just filter them as NAN
  total += +item ? +item : 0;
});

console.log(total);
```

**Comment by having-fun-coding** [comment]
@sidorares 

function plus(x,y) { return x+y };
console.log(process.argv.slice(2).map(Number).reduce(plus));

Number above is just a parameter?

**Comment by sidorares** [comment]
@having-fun-coding yes, it's a reference to a `Number` function which is a constructor for built-in Number object. The result of `[1, 2, 3, "4.56"].map(Number)` is `[Number(1), Number(2), Number(3), Number("4.56")]` array - basically it's a fancy functional way to convert all array elements to numbers a bit more verbose version:

```js
function plus(x,y) { return x+y }
function convertToNumber(src) { return Number(src); }
console.log(process.argv.slice(2).map(convertToNumber).reduce(plus));
```

**Comment by MichaelLSmith** [comment]
I'm a relative newbie. Can someone explain how this part of the first example works?
I understand +item converts a string to an integer. And I know ? : is shorthand for an if statement. But I don't understand how the 0 filters out the first two items in the process.argv array. Thanks in advance for any help.

```
total += +item ? +item : 0;
```

**Comment by vitkarpov** [comment]
> But I don't understand how the 0 filters out the first two items in the process.argv array

They don't. For the first to items we get zero and it just doesn't affect the sum.

**Comment by Tinker-S** [comment]
var total = 0;
for (var i = 2; i < process.argv.length; i++) {
    total += Number(process.argv[i]);
}
console.log(total);
