### ISSUE TITLE
Error on attempting to run `learnyounode`

### ISSUE THREAD

**Issue by richorama** [workshopper/learnyounode#87]
Not sure if this is an issue with learnyounode or workshopper (or mkdirp!), but after successful installation, running 'learnyounode' threw an error on a Windows machine:

```
D:\Data\NodeJS\nodeSchool>learnyounode

D:\AppData\goffinf\Application Data\npm\node_modules\learnyounode\node_modules\workshopper\node_modules\mkdirp\index.js:74
                    throw err0;
                          ^
RangeError: Maximum call stack size exceeded
```

This was on the attendee's machine at a node school IRL event, and I have been unable to replicate.

**Comment by a0viedo** [comment]
@richorama is this resolved?

**Comment by richorama** [comment]
Yeah, I never heard anything back.
