### ISSUE TITLE
Code in the solarized color theme is not displayed correctly 

### ISSUE THREAD

**Issue by willprice** [workshopper/learnyounode#96]
Hi,

I've been following along `learnyounode` and have found that it doesn't play nicely with terminals that use the popular _solarized_ color theme.

![2014-04-15-172922_245x190_scrot](https://cloud.githubusercontent.com/assets/966205/2709886/21d330a2-c4bb-11e3-915f-850ee83c80ec.png)

The theme can be found [here](https://github.com/altercation/solarized)

Any chance a modification can fix this? `Mocha` also has this problem with it's reporters, but the maintainer is unwilling to fix this as he says it's a solarized issue.

Relevant threads:
https://github.com/altercation/solarized/issues/220
https://github.com/visionmedia/mocha/issues/802
https://github.com/yeoman/yeoman/issues/386

Not sure whether you consider this something to fix, or not. At least if others experience the same problem they can try and modify the solarized theme!

**Comment by shanmukhateja** [comment]
This issue can be marked as closed due to inactivity. Feel free to reopen the issue if you have something to contribute to it.
